### ISSUE TITLE
Wrong admin form is shown for translated FlatPage

### ISSUE THREAD

**Issue by deschler** [deschler/django-modeltranslation#14]
_Original author: federico.maggi (October 14, 2009 23:23:24)_

Steps will reproduce the problem:
1. follow the InstallationAndUsage
2. add:

from django.contrib.flatpages.models import *
class FlatPageTranslationOptions(TranslationOptions):
    &quot;&quot;&quot;
    Translation of `FlatPage`.
    &quot;&quot;&quot;
    fields = (
        'title',
        'content', )
translator.register(FlatPage, FlatPageTranslationOptions)
1. python manage.py syncdb
2. visit the admin interface

Problem: fields are not translated even if title_\* content_\* are in the database.

_Original issue: http://code.google.com/p/django-modeltranslation/issues/detail?id=14_

**Comment by MamatmurodovA** [comment]
In my flatpage had ckeditor , but when i add to admin.py this code 
def form_field(self, db_field, **kwargs):
        field = super(FlatPageAdmin, self).form_field(db_field, **kwargs)
        self.patch_translation_field(db_field, field, **kwargs)
        return field
it doesn't support ckeditor, but why ?
