### ISSUE TITLE
Making unittest using models with translated fields

### ISSUE THREAD

**Issue by dnmellen** [deschler/django-modeltranslation#200]
Hi, I'm trying to make some unittests and I have a problem with the current version of django-modeltranslation.

I'm creating objects in test's `setUp()` but since this code runs outside a django view it's failing and giving me this exception:

`Category` model has some translated fields, `name` is one of them.

```
cat = Category.objects.create(catalog=c, name="Category one")

TypeError: 'name_es' is an invalid keyword argument for this function
```

I really need to create objects in test code, Is there some way to achieve this?

**Comment by decibyte** [comment]
@dnmellen, I know it's a long time ago now, but did you happen to also be using `django-audit-log` at the same time? In that case (and for others coming here), I found out you also have to remember to register your audit log models for translation. As seen in [this example](https://github.com/decibyte/django-auditlog-modeltranslation-testcase/compare/fix?expand=1#diff-f5e2c57158f98362114fabca111c67dfR7).

**Comment by ice3** [comment]
It's a really old issue, but I saw it while debugging the same issue. 
When you call the management command, don't forget to make the migration before running the tests.
