### ISSUE TITLE
Problem SlugField with django 1.6

### ISSUE THREAD

**Issue by ghost** [deschler/django-modeltranslation#221]
I use a SlugField with modeltranslation and I have a problem.

This is my code:
- models.py

``` py
class News(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(blank=True, null=True)

    def __unicode__(self):
        return self.title
```
- admin.py

``` py
class NewsAdmin(admin.ModelAdmin):
    list_display = ('title',)
    prepopulated_fields = {'slug': ('title',)}

admin.site.register(News, NewsAdmin)
```
- translation.py

``` py
class NewsTranslationOptions(TranslationOptions):
    fields = ('title', 'slug')

translator.register(News, NewsTranslationOptions)
```

When I add an item through admin I obtain the following error:

'NoneType' object has no attribute 'strip'
Request Method: POST
Request URL:    http://mysite/admin/myapp/news/add/
Django Version: 1.6.1
Exception Type: AttributeError
Exception Value:  
'NoneType' object has no attribute 'strip'
Exception Location: /myvirtualenv/lib/python2.7/site-packages/django/forms/fields.py in clean, line 1142

**Comment by ygwain** [comment]
The issue doesn't resolved for me. I did as described in the docs:
http://django-modeltranslation.readthedocs.org/en/latest/forms.html#formfields-and-nullability
Quote:
> This configuration is especially useful for fields with unique constraints:
```python
> class Category(models.Model):
>     name = models.CharField(max_length=40)
>     slug = models.SlugField(max_length=30, unique=True)
```
> Because the slug field is not nullable, its translation fields would store empty values as '' and that would result in an error when two or more Categories are saved with slug_en empty - unique constraints wouldn’t be satisfied. Instead, None should be stored, as several None values in the database don’t violate uniqueness:
```python
> class CategoryTranslationOptions(TranslationOptions):
>     fields = ('name', 'slug')
>     empty_values = {'slug': None}
>
```

But this did not work. I got same exception.

P.S. I use Django 1.6 too.

**Comment by zlorf** [comment]
@ygwain, please see #353 for a solution.
