### ISSUE TITLE
Dynamic field classes fail with version 2.4 of Django REST Framework

### ISSUE THREAD

**Issue by tituomin** [deschler/django-modeltranslation#263]
If somebody is using Django REST Framework, version 2.4 surfaced a deeper problem with integrating DRF with django-modeltranslation.

django-modeltranslation is using the fields.field_factory function which dynamically creates a new class on each invocation as a subclass of the model field class. Django REST Framework has a serializers.field_mapping which can be modified to ensure any model field classes are mapped to correct REST framework field classes.

A change in REST Framework 2.4 added a CharField-specific modification which causes a failure with modeltranslation subclasses of CharField, because the correct REST Framework method is not called.
https://github.com/tomchristie/django-rest-framework/issues/1809

This cannot be fixed in the normal way, because REST Framework uses classes as dictionary keys, and this in turn is dependent on the standard "type" metaclass **hash** and **eq** methods, as I understand, which give different results for every dynamic class created by an invocation of fields.field_factory. That is, the created classes are all inequal to each other.

If we want to be able to interoperate with REST Framework, I believe a new metaclass should be created which calls the **hash** and **eq** methods in the context of the base class, for example CharField. I might have time to dig into this later, but I'm not sure if this kind of a solution would brake anything.

**Comment by StErMi** [comment]
Hi, could you provide a full working example?
