### ISSUE TITLE
TabbedTranslationAdmin with no actionable fragment

### ISSUE THREAD

**Issue by helderco** [deschler/django-modeltranslation#270]
Currently with `TabbedTranslationAdmin`, when a tab is clicked, the screen scrolls to the top of the field, hiding the tabs themselves (assuming your form is bigger then your screen), because of the URL fragment (e.g. `#tab_id_description_pt`).

![tabbedtranslationadmin](https://cloud.githubusercontent.com/assets/174525/4559125/73e8be36-4ee8-11e4-8564-1a2c4c18edaa.png)

This is very annoying, especially if I want to quickly move into the other languages to check any missing or misspelled translations. I have to constantly scroll back up a bit to see the tabs.

It would be better if de fragment would target the top of the tabs instead of the field, but what would be ideal is to not scroll to anywhere at all, thus having the fragment not be actionable (empty return inside a click event in javascript).

**Comment by fabiocaccamo** [comment]
The scroll is very annoying, it can be easily solved by using hashes different by tab ids, for example if the tab id is **#tab_id_name_en** the hash could be **#tab_name_en**.

In this way the work to do is to intercept the click, get the id, create the hash by replacing **#tab_id** with **#tab_**, then update the document location with the new hash.

**Comment by fabiocaccamo** [comment]
@helderco @sunjoomoon @deschler I just fixed it and sent pull-request: https://github.com/deschler/django-modeltranslation/pull/297

**Comment by shamuratov6563** [comment]
nice
