### ISSUE TITLE
Make it configurable to return default language value or empty if translated field is empty

### ISSUE THREAD

**Issue by deschler** [deschler/django-modeltranslation#28]
_Original author: bmihe...@gmail.com (June 15, 2010 08:16:05)_

For many cases it would be useful to just return empty string instead of value of default language. 

Foe example, for some product we have only summary in target language and do not want to clutter page with content in other language.

This could be made as setting for TranslationOptions with default behavior as is current implementation:

```
class NewsTranslationOptions(TranslationOptions):
    fields = ('title', 'text',)
    default_translate = False # default is True
```

If you found this sensible let me know and I will create a patch.

_Original issue: http://code.google.com/p/django-modeltranslation/issues/detail?id=28_

**Comment by rubenanapu** [comment]
Assuming I have a model with a `title` field, to return the value of the original field/column when there are no translations for a given language, and all fallback fields are empty, what I did was the following:

I just modified the last line of [`TranslationFieldDescriptor.__get__`](https://github.com/deschler/django-modeltranslation/blob/master/modeltranslation/fields.py#L412) to the following

```diff
-           return default
+           return default or instance.__dict__[self.field.name]
```

In my tests, it seems to be working as I expected. Better (for me) than having empty fields all over the place.

I know _**./manage.py update_translation_fields**_ helps somehow if we just integrate _**modeltranslation**_ in the project, but when new people add new entries to the database, this command wouldn't help. 

Anyway. The changes I mentioned here solved my problem. The reason why I documented it here is that it may help someone else.

**Comment by tmertensacker** [comment]
How is it possible to achieve what the original question was (return empty string instead of value of default language for a specific field) with the current settings available (fallback_languages, fallback_values, fallback_undefined)?
