### ISSUE TITLE
There is a Roadmap to Django 1.8 support ?

### ISSUE THREAD

**Issue by azman0101** [deschler/django-modeltranslation#295]
I get an error when using modeltranslation with Django 1.8a1

```python
/local/lib/python2.7/site-packages/modeltranslation/manager.py", line 12, in <module>
    from django.db.models.fields.related import RelatedField, RelatedObject
ImportError: cannot import name RelatedObject
```

When do you think django-modeltranslation will support 1.8 ?

**Comment by zlorf** [comment]
Thanks for the info, will check this.

**Comment by azman0101** [comment]
Hi,

My knowledge of Django is very limited but I've tried something:

Like it's said in documention of Django:
```
Remove django.db.models.related.RelatedObject
For version > 1.7
https://code.djangoproject.com/ticket/21414#comment:10
```
I've tried the change mentionned in comment:
https://github.com/azman0101/django-modeltranslation/commit/d72677ddf670759410c0581035be91fc76135a2e

I didn't found why the remove parent_model:
https://github.com/azman0101/django-modeltranslation/commit/8d6822c13f5218a596d3fc76e9fb1be8635bcf47

When the unitest comes to "related test", there are some errors.

Thxs

**Comment by zlorf** [comment]
See #299, moving all 1.8-related discussion there.
