### ISSUE TITLE
AttributeError: 'Options' object has no attribute 'module_name' in Django 1.8

### ISSUE THREAD

**Issue by gilguilherme** [deschler/django-modeltranslation#310]
python manage.py sync_translation_fields command:

File "/django_1.8/lib/python2.7/site-packages/modeltranslation/management/commands/sync_translation_fields.py", line 70, in handle_noargs
    model_full_name = '%s.%s' % (model._meta.app_label, model._meta.module_name)
AttributeError: 'Options' object has no attribute 'module_name'

In Django 1.8 Model._meta.module_name was renamed to model_name.

**Comment by deschler** [comment]
Fixed the deprecation, but i'm afraid there's more. Now fails at `transaction.commit_unless_managed()`. I'll have another look later.

**Comment by deschler** [comment]
From what i can tell by reading the docs, `transaction.commit_unless_managed()` is handled by the transaction system automatically since Django 1.6. It can be disabled for newer versions.

**Comment by gilguilherme** [comment]
Good job! ;)
