### ISSUE TITLE
How to do a data migration from existing field to default language?

### ISSUE THREAD

**Issue by edouard-lopez** [deschler/django-modeltranslation#319]
#### `models.py`

``` py
from django.db import models

class Service(models.Model):
    name = models.CharField(max_length=100)
    url = models.CharField(max_length=300)

    def __str__(self):
        return self.name
```
#### `translation.py`

``` py
from modeltranslation.translator import translator, TranslationOptions
from portal.models import Service

class ServiceTranslationOptions(TranslationOptions):
    fields = ('name', 'description')

translator.register(Service, ServiceTranslationOptions)
```
#### `admin.py`

``` py
from django.contrib import admin
from modeltranslation.admin import TabbedTranslationAdmin
from portal.models import Service

class ServiceAdmin(TabbedTranslationAdmin):
    pass

admin.site.register(Service, ServiceAdmin)
```

**Comment by RamiAhmed** [comment]
This question is quite relevant for me as well.

We have an existing database in english. When I run makemigrations with translations enabled, all the fields marked for translation are cleared so that all translation fields are empty. This is unacceptable for us. 

We need to be able to use the current data in the database for the language marked as default. Also, we would not want to have to fill out all the "_en" fields, as we already have it in english. Frankly, I'm surprised that the "_en" columns were added, considering that it should just use whatever is presently there?

Hoping for a speedy resolution to this issue!

**Comment by fabiocaccamo** [comment]
If you look into the db you will see that original fields are not cleared, but (actually) you will not retrieve anymore their value using the orm.

I think there are 2 solutions:

1. When migrating, all values should be duplicated to populate the default language field and after optionally cleared to avoid duplicated values for each row (this will work fine with the admin).

2. The default language field if empty try to get the value from the original field (I'm not sure about how this solution could work with the admin)

**Comment by RamiAhmed** [comment]
Actually I found the answer in the excellent documentation:
http://django-modeltranslation.readthedocs.org/en/latest/commands.html#the-update-translation-fields-command

Using the command update-translation-fields, all my problems were solved. Thanks!

**Comment by SeanHayes** [comment]
I have the same issue.

So, the original column is left in the DB, but it can never be accessed? Is it safe to use a migration to rename 'name' to 'name_en"? Or is there a way to let 'name' be edited in the admin and not generate 'name_en' at all?

**Comment by SeanHayes** [comment]
OK, so renaming doesn't work, I get this error:
no such column: model.name

Seems kind of pointless to have that column if it can never be accessed (and if future changes to the English never get written back to it).

**Comment by zlorf** [comment]
@SeanHayes See https://github.com/deschler/django-modeltranslation/issues/344

**Comment by mariuszjamro** [comment]
I made a management command to fill the data for me. Maybe we can add that to `django-modeltranslation` ?

    from django.core.management.base import BaseCommand
    from django.db import transaction
    from django.conf import settings

    class Command(BaseCommand):

        @transaction.atomic
        def handle(self, *args, **options):
            from modeltranslation.translator import translator

            for model, options in translator._registry.items():
                if not options.fields: continue

                for item in model.objects.all():

                    for field in options.fields:

                        value = getattr(item, field)
                        if value is None:  
                            setattr(item, field, value)
                            item.save()

**Comment by mariuszjamro** [comment]
I made a management command to populate the initial data. It basically performs a query for each translatable model doing something like:

     UPDATE table SET a_column_XX = a_column

where XX is the default language. I'm using Django 1.9

    from django.core.management.base import BaseCommand
    from django.db import transaction
    from django.conf import settings
    from django.db.models import Func

    class RawColumn(Func):
        template = '%(expressions)s'

    class Command(BaseCommand):

        @transaction.atomic
        def handle(self, *args, **options):
            from modeltranslation.translator import translator

            for model, options in translator._registry.items():
                if not options.fields:
                    continue

                columns_to_populate = dict()
                for translatable_field in options.fields:

                    column_to_populate = '%s_%s' % (translatable_field, settings.LANGUAGE_CODE)

                    model_field = [field for field in model._meta.fields if field.name == translatable_field]
                    if not model_field:
                        raise Exception("Model field not found")

                    attname, raw_column_name= model_field[0].get_attname_column()

                    columns_to_populate[column_to_populate] = RawColumn(raw_column_name)

                if columns_to_populate:
                    model.objects.update(**columns_to_populate)

**Comment by raeesaroj** [comment]
> Actually I found the answer in the excellent documentation:
> http://django-modeltranslation.readthedocs.org/en/latest/commands.html#the-update-translation-fields-command
> 
> Using the command `update_translation_fields`, all my problems were 


> Actually I found the answer in the excellent documentation:
> http://django-modeltranslation.readthedocs.org/en/latest/commands.html#the-update-translation-fields-command
> 
> Using the command `update_translation_fields`, all my problems were solved. Thanks!

Thanks it works

**Comment by vishal2612200** [comment]
> Actually I found the answer in the excellent documentation:
> http://django-modeltranslation.readthedocs.org/en/latest/commands.html#the-update-translation-fields-command
> 
> Using the command `update_translation_fields`, all my problems were solved. Thanks!

Thanks, @RamiAhmed, This worked for me, after around 5 years also.
