### ISSUE TITLE
Creation of an option to prevent specifics URLs to have a language slug

### ISSUE THREAD

**Issue by SebasSBM** [deschler/django-modeltranslation#322]
It would be a good idea to create some kind of parameter that allows preventing specific URL patterns from have a language slug and being translated. This would be because some URLs (like the ones for dynamically generated sitemaps in XML) are not necessary to be translated, and it is an inconvenient that they get forced to have an '/en/' like slug for languages in the URLs. In addition, it ends up creating two different sitemaps for each language.

I've read all the CHANGELOG entries to find out if this feature already exists or not, but it seems it doesn't.

**Comment by deschler** [comment]
Modeltranslation does not mess with views or urls. It is up to your project or application to implement such a behaviour.

Moreover urls aren't prefixed in Django by default. If your urls are prefixed, you are likely using Django's internal i18npatterns. Perhaps all you need is a normal urlpattern.

**Comment by SebasSBM** [comment]
Sorry for the confusion. I'll close this issue inmediately.
