### ISSUE TITLE
group_fieldsets leaves ManyToMany fields out

### ISSUE THREAD

**Issue by akheron** [deschler/django-modeltranslation#332]
When using group_fieldsets, ManyToMany fields are not displayed in the admin anymore. I think this happens because ManyToMany fields are not listed in Model._meta.fields.

**Comment by akheron** [comment]
In `django.forms.models.fields_for_model` function, model's fields are discovered like this:

```python
    from django.db.models.fields import Field as ModelField
    sortable_virtual_fields = [f for f in opts.virtual_fields
                               if isinstance(f, ModelField)]
    for f in sorted(chain(opts.concrete_fields, sortable_virtual_fields, opts.many_to_many)):
    ....
```

Using this kind of list instead of `self.opts.fields` should fix the problem.

**Comment by blaise-io** [comment]
I'm also having this issue in Django 1.7.
