### ISSUE TITLE
show all fields on admin list.

### ISSUE THREAD

**Issue by fapelhanz** [deschler/django-modeltranslation#337]
So I have the model "News", with the field "text" translatable into "en" and "es", but when I enter the django admin on the News list, I can only see one column for that field showing the current translation instead of 2 (one for english, and one for spanish) like when I see when I edit one of the news, is there any way around this other than doing this:

```
from modeltranslation.utils import get_translation_fields

class News(TranslationAdmin):
    _list_display = ('page', 'key')
    list_display = _list_display + tuple(get_translation_fields('text'))

    search_fields = list_display
```

regards.

**Comment by bartmika** [comment]
+1

**Comment by lozhkinandrei** [comment]
@fapelhanz might be a bit cleaner
```
from modeltranslation.utils import get_translation_fields


class News(TranslationAdmin):
   list_display = (
       *get_translation_fields('text'),
       'page', 
       'key',
   )
   search_fields = list_display
```
