### ISSUE TITLE
Philosophical question about having duplicated datas in the DB

### ISSUE THREAD

**Issue by martync** [deschler/django-modeltranslation#344]
Hi, 

I'm about to choose an application to translate an existing project and I've tried django-modeltranslation, which is excellent, bravo ! 

I have a doubt about something and after reading the doc, I'm not 100% sure I've got it. 
My project is french and all the content in the DB is written in french. I will add the english language (I already have i18n and localisation files).

After setting this : 
```python
MODELTRANSLATION_DEFAULT_LANGUAGE = 'fr'

@register(MyModel)
class MyModelTranslationOptions(TranslationOptions):
    fields = ('title', )
```

The migration will create : **title_fr** and **title_en**. 
I can't explain why I need to have a both title + title_fr fields that will normally have the same value 100% of the time. Having duplicated datas in the DB is source of errors. 
I've searched in many places to know why, with no success. 

Thanks for reading.

**Comment by zlorf** [comment]
Well, that was a project decision that needed to be taken and I think it was explained somewhere, but I can't find where. Maybe @deschler will remember better that me.

As far as I remember, there were two main reasons:
1. Code simplicity
2. Ability to change `MODELTRANSLATION_DEFAULT_LANGUAGE` without being forced to change database field names (e.g. if `title` hold French version and `title_en` English one, then changing default language to English would mean that those fields should be named `title_fr` and `title`, respectively).

**Comment by martync** [comment]
Thanks for answering. So this is a design decision, I was expecting that answer and wanted to make sure that this is not part of a todo list, because I would think that most of the i18n sites don't change its base language during its life. 
Anyway, definitely a great app !
