### ISSUE TITLE
Tip, any way to remove unused language fields?

### ISSUE THREAD

**Issue by sunjoomoon** [deschler/django-modeltranslation#347]
I created a few languages and wish to remove unused language fields. Any management command for this? or other ways to achieve this?

**Comment by zlorf** [comment]
You mean you reduced number of languages?
Standard Django migrate command should detect that fields were removed.

**Comment by sunjoomoon** [comment]
Initially I created a few languages, and later just use two languages only. Till all okay, just uncomment unused languages - admin and db level, all okay. Now, I tried to dumpdata and loaddata which checks integrity and complains about the integrity. This all makes sense though - checking app's models, translation vs actual db fields. 

So wondered if anything like ```sync_translation_fields``` exists but compare languages vs fields and remove any unused fields.
