### ISSUE TITLE
Add support ArrayField

### ISSUE THREAD

**Issue by liminspace** [deschler/django-modeltranslation#352]
I propose support posgres' fields like ArrayField.

**Comment by zlorf** [comment]
Try adding in your settings.py:
`MODELTRANSLATION_CUSTOM_FIELDS = ('ArrayField',)`

http://django-modeltranslation.readthedocs.org/en/latest/installation.html#modeltranslation-custom-fields

**Comment by liminspace** [comment]
Thanks! :+1:

**Comment by murdav** [comment]
But while saving the item in the admin I get:

```
  File "*/site-packages/django/contrib/postgres/forms/array.py", line 65, in validate
    for index, item in enumerate(value):
TypeError: 'NoneType' object is not iterable

```
In the doc there is also written:

`This just prevents modeltranslation from throwing an ImproperlyConfigured exception. Any unsupported field will most likely fail in one way or another. The feature is considered experimental and might be replaced by a more sophisticated mechanism in future versions.
`

Anyi deas on how this can be achieved?
