### ISSUE TITLE
Slug with unique constraint => 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by ppo** [deschler/django-modeltranslation#353]
With the following:
```
class MyModel(models.Model):
    slug = models.SlugField('slug', blank=True, max_length=50, null=True, unique=True)

@register(MyModel)
class MyModelTranslationOptions(TranslationOptions):
    fields = ("slug",)
    empty_values = {"slug": None}
```

Creating a record (via the admin for example) with an empty value for `slug` produces the error: "AttributeError: 'NoneType' object has no attribute 'strip'".
It's raised when `SlugField.clean()` is called, executing `value = self.to_python(value).strip()`.
Source code: https://github.com/django/django/blob/1.8.7/django/forms/fields.py#L1258

**Comment by zlorf** [comment]
Unfortunatelly the `SlugField` always call `strip()` on value, being `None` in this case.
You can:
- update to Django 1.9 which seems to have fixed the issue
- Use `FixedSlugField` instead of normal `SlugField` (not tested):
```python
class FixedStripSlugField(forms.SlugField):
    def clean(self, value):
        value = self.to_python(value)
        if isinstance(value, six.string_types):
            value = value.strip()
        return super(SlugField, self).clean(value)  # bypassing SlugField's clean

class FixedSlugField(models.SlugField):
    def formfield(self, **kwargs):
        defaults = {'form_class': FixedStripSlugField}
        defaults.update(kwargs)
        return super(FixedSlugField, self).formfield(**defaults)
```

**Comment by SalahAdDin** [comment]
can you solve this soon?

**Comment by zlorf** [comment]
Didn't I post a solution, or even two?

**Comment by ppo** [comment]
Thanks @zlorf. Your `FixedSlugField` solution works fine. Didn't test with Django 1.9 but it seems it will work too.
