### ISSUE TITLE
would it be possible to make some individual objects untranslated?

### ISSUE THREAD

**Issue by divinites** [deschler/django-modeltranslation#373]
For example, I have a blog written in two languages. Not all blog post haves versions of all languages. e.g. Some blog posts are only available in English, Some are only available in Chinese,  Others have both versions available. 

What I want to do is to show corresponding blogs that the request.LANGUAGE_CODE refers to. That means I would like to have some single-language blog post untranslated, thus it won't show up in all language settings. Would it be possible?

**Comment by zlorf** [comment]
If I understand you correctly, you want to filter blog posts and show only those that are translated to current language.
You can do it using something like `Post.objects.exclude(title="")` to don't retrieve posts that don't have title in current language.

**Comment by divinites** [comment]
great! thanks. issue closed.
