### ISSUE TITLE
Translated models doesn't return flat annotated values_lists

### ISSUE THREAD

**Issue by ziima** [deschler/django-modeltranslation#374]
Translated models returns list of tuples when queryset is build as `values_list(...,  flat=True).annotate(...)`. Expected behaviour is to return list of values regardless of the order of `values_list` and `annotate` calls.

Found using django-modeltranslation 0.11 and django 1.7 and 1.8

##### Example #####
```python
# Untranslated model
>>> Foo.objects.values_list('year', flat=True).annotate(Count('year'))
[1991, 1992, 1993, 1994, ...]
# Translated model
>>> Bar.objects.values_list('year', flat=True).annotate(Count('year')) # Unexpected result
[(1991, 2), (1992, 1), (1993, 5), (1994, 7), ...]
# Same output is given when `flat` is not used
>>> Bar.objects.values_list('year').annotate(Count('year'))
[(1991, 2), (1992, 1), (1993, 5), (1994, 7), ...]
```

_Edit: I removed the cases `annotate(...).values_list(...)`, because it performs different queries, both in django and modeltranslation._

**Comment by zlorf** [comment]
The good news is that it works as expected in Django 1.9.

Fixing it for 1.7 and 1.8.
