### ISSUE TITLE
Rule 2 (Assigning a value to the original field ...) broken for Deferred models

### ISSUE THREAD

**Issue by Paul424** [deschler/django-modeltranslation#379]
After doing some query enhancements i noticed the second rule as per docs from modeltranslations (i.e.: Rule 2: Assigning a value to the original field updates the value in the associated current language translation field.) seems to be broken when only a subset of fields is loaded using only( ).

The dangerous thing is that no exception is raised; the assignment just does not change the state of the instance.

I run version 0.10.2

Explained in an example:

>>> o=Pack.objects.only('description').get(code='ABC')
>>> o
<Pack_Deferred_...: 4005>
>>> o.description
u'text here'
>>> o.description=u'bla'
>>> o.description
u'text here' <=== no exceptions, but new value not set on instance?
>>> o=Pack.objects.get(code='ABC')
>>> o
<Pack: ...>
>>> o.description
u'text here'
>>> o.description=u'bla'
>>> o.description
u'bla' <=== as expected

**Comment by zlorf** [comment]
The problem confirmed; I'll fix this soon.
