### ISSUE TITLE
[Question] How to save data for only a specific language

### ISSUE THREAD

**Issue by StErMi** [deschler/django-modeltranslation#390]
I'm using MT to grab data from an API and I would like to save those that only for a specific language.
Is it possibile to do that without manually set data for each field for that specific language?

Cheers, Emanuele.

**Comment by zlorf** [comment]
You mean you create model (from an API) with many field and many languages, like `title_en`, `title_de`, `content_en`, `content_de`, and you want only to save `*_en` to database?

**Comment by StErMi** [comment]
I want to be able to select which language to use when I save those data from API.
Actually, as far as I see from docs, I need to set those values manyally.

I would like to have something like

```python
model = Model()
model.setLanguage('it')
```

After that every changes to that model will be saved to every *_it field (if exists)

**Comment by zlorf** [comment]
Ah, I see. You need to set proper language context, https://docs.djangoproject.com/en/dev/ref/utils/#django.utils.translation.activate

```
from django.utils import translation
with translation.override('it'):
    model = Model()
    # set fields, like model.title = 'XYZ'
    model.save()
# back to previous language
```

**Comment by StErMi** [comment]
@zlorf don't you think this should be a feature inside MT? Or everyone is using MT to insert data from crowdsourced source? (in this case it will use browser language)

**Comment by zlorf** [comment]
MT was developed for request-based language detection.
http://django-modeltranslation.readthedocs.io/en/latest/caveats.html#accessing-translated-fields-outside-views
Your use-case is rare, but - as shown above - one can easily set language and no additional code in MT is needed for this. Maybe adding this example to the mentioned docs' page would be good idea.

**Comment by StErMi** [comment]
Thank you for your help zlorf, I think that we can close it. How can I suggest an update to the docs?

**Comment by SalahAdDin** [comment]
@StErMi you can open a new issue with your ask.
