### ISSUE TITLE
modeltranslation.translator.NotRegistered: The model "Project" is not registered for translation

### ISSUE THREAD

**Issue by XaviP** [deschler/django-modeltranslation#408]
Using python 3.4, django 1.11, and django-modeltranslation 0.12:
when TranslationAdmin is extended, django gives error:
```
  File "clowns/projects/admin.py", line 23, in <module>
    admin.site.register(Project, ProjectAdmin)
  File "env/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 125, in register
    self._registry[model] = admin_class(model, self)
  File "env/lib/python3.4/site-packages/modeltranslation/admin.py", line 250, in __init__
    super(TranslationAdmin, self).__init__(*args, **kwargs)
  File "env/lib/python3.4/site-packages/modeltranslation/admin.py", line 34, in __init__
    self.trans_opts = translator.get_options_for_model(self.model)
  File "env/lib/python3.4/site-packages/modeltranslation/translator.py", line 621, in get_options_for_model
    'translation' % model.__name__)
modeltranslation.translator.NotRegistered: The model "Project" is not registered for translation

```
projects/models.py
```
class Project(models.Model):
    name = models.CharField(max_length=255, verbose_name=_("Name"))
    text = models.TextField(verbose_name=_("Description"))
```
projects/translation.py
```
@register(Project)
class ProjectTranslationOptions(TranslationOptions):
    fields = ('name', 'text',)
```
projects/admin.py
```
class ProjectAdmin(TranslationAdmin):
    pass

admin.site.register(Project, ProjectAdmin)
```

**Comment by XaviP** [comment]
Ups! Now I see your last commit https://github.com/deschler/django-modeltranslation/commit/45097424e421c99799d776e45c98f820545fa8f2, so I'll wait for 0.13

**Comment by madEng84** [comment]
@XaviP try putting 'modeltranslation' before 'django.contrib.admin' in your INSTALLED_APPS and disabling django_debug_toolbar as workaround.

However ./manage.py update_translation_fields seems to be broken

Let's wait for 0.13

**Comment by neulaender** [comment]
Using `django-modeltranslation==0.13b1` and putting the "modeltranslation" app before the admin finally worked for me with `django==2.1.1`. Just in case someone wonders. I hope it's stable enough, as I'm dependent on `django >= 2` and on translatable model fields. 

Is there anything someone could do to help out making this more stable? I never helped in open source projects, but maybe there are some minor tasks where I could help?

**Comment by om2c0de** [comment]
Thanks, @madEng84 - 'modeltranslation' before 'django.contrib.admin' fixed errors for me ;)
