### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dmarcelino** [deschler/django-modeltranslation#448]
Hi @deschler and @zlorf,

First of all let me start by saying `django-modeltranslation` is a great package, thank you and all contributors.

Recently I've started collaborating to [wagtail-modeltranslation](https://github.com/infoportugal/wagtail-modeltranslation/) (which adds modeltranslation support to Wagtail) and amidst some code changes we hit the issue that PR  #431 fixes. We are about to release a new version of `wagtail-modeltranslation` but we are dependant on code living on modeltranslation's master branch.

Are there any plans to push out a new version soon? Is there anything blocking a new release that we can help with?

Thanks!

**Comment by deschler** [comment]
Please try 0.12.2 for Django 1.11. Django 2.0 support is still in development.
