### ISSUE TITLE
base_manager uses default_manager

### ISSUE THREAD

**Issue by Sult** [deschler/django-modeltranslation#455]
In our project we figured out that overwriting the base_manager_name is not a good idea.
model._meta.base_manager_name = 'objects'
https://docs.djangoproject.com/en/2.0/topics/db/managers/#base-managers
https://github.com/deschler/django-modeltranslation/commit/a7b484d10aa16003a7d912332744699fbbc23014

Since now it gets set to the normal objects manager, whatever is done there now also happens in the related lookups. When you now use your own manager (that use extra filtering) on a model that also uses modeltranslation, related lookups (can) break

**Comment by flixx** [comment]
I just encountered the same problem after upgrading django. MySQL gave me just a wired `"Duplicate entry '3' for key 'PRIMARY"` error because there was a `WHERE` clause in the update query, which was coming from our custom objects Manager. After the `UPDATE` fails, Django tries to insert the updated object again.

So I agree with @Sult that overwriting the base_manager should not be done.

**Comment by wrvdklooster** [comment]
Is this planned to be solved?

**Comment by syre** [comment]
Also having this problem but @flixx workaround seems to work.

**Comment by wrvdklooster** [comment]
Any idea if this will fixed anytime soon?

**Comment by last-partizan** [comment]
@wrvdklooster as soon as someone will dig into issue and make pull-request. I haven't figured how this can be fixed in a reasonable manner.

**Comment by last-partizan** [comment]
https://www.bountysource.com/issues/55659673-base_manager-uses-default_manager

Let's try this, throw money here until someone make a fix.

**Comment by wrvdklooster** [comment]
Sounds fair, will donate.

**Comment by b0g3r** [comment]
Hmm... Why modeltranslation need to overwrite `base_manager_name` to `'objects'`? As I see django and modeltranslations works as expected without explicit overwriting 🤔

**Comment by last-partizan** [comment]
@b0g3r i don't know, but without it tests is failing

```
======================================================================
FAIL: test_reverse_relations (modeltranslation.tests.tests.ForeignKeyFieldsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/serg/work/git/django-modeltranslation/modeltranslation/tests/tests.py", line 984, in test_reverse_relations
    self.assertIn(fk_inst_both, test_inst2.test_fks.all())
AssertionError: <ForeignKeyModel: ForeignKeyModel object (1)> not found in <MultilingualQuerySet []>
```

**Comment by Sult** [comment]
I am new to contributing to a package.
How do i link this issue to my PR?
https://github.com/deschler/django-modeltranslation/pull/537

**Comment by last-partizan** [comment]
Just mention it there, or PR here. I'll take a look :)
