### ISSUE TITLE
test_reverse_relations, test_select_related fail on Django 2.0

### ISSUE THREAD

**Issue by stuaxo** [deschler/django-modeltranslation#457]
I've been having a go at getting wagtail-model translation working with wagtail 2.

The unit tests for my PR are passing now, but it requires django-modeltranslation from installed from git

Is there a release of django-modeltranslation coming up, so I can make the dependency be installed from pypi instead ?

**Comment by karolyi** [comment]
+1, waiting for the release.

**Comment by dmarcelino** [comment]
Looking at the latest `django-modeltranslation` build ([link](https://travis-ci.org/deschler/django-modeltranslation/jobs/335590954#L640)) there are still 2 test failures:

```
FAIL: test_reverse_relations (modeltranslation.tests.tests.OneToOneFieldsTest)
FAIL: test_select_related (modeltranslation.tests.tests.TestManager)
```

That's likely what's holding a new release. Unfortunately there doesn't seem to be any open PRs to address those.

**Comment by stuaxo** [comment]
Good point, I'm not sure how useful this "bug" is, I've changed the title so this is hopefully somewhat more useful.

**Comment by dmarcelino** [comment]
PR #462 looks promising!

**Comment by dmarcelino** [comment]
@deschler, thanks for merging PR #462! Since Django 2.0 tests are now passing when can we expect a `0.13` release? If you don't think we are there yet, perhaps release an alpha or beta version so people have something they can download from pypi and test?

Cheers

**Comment by deschler** [comment]
Hi Dario. Thanks alot for fixing the remaining issues! I have just released 0.13-beta1 so people can test it with Django 2.0.

**Comment by dmarcelino** [comment]
@abdolhosein, @PetrDlouhy and @GreyZmeem are the real heroes! I'm just the guy nagging you about PRs and releases. 😊 

PS: you can also close #460

**Comment by karolyi** [comment]
what's the status on this one? I'm waiting eagerly for the django 2.x compatible modeltanslation module.

**Comment by ukharov-epiit** [comment]
Any plans on the release date?

**Comment by aburdakov** [comment]
Any plans on the release date?

**Comment by nealtodd** [comment]
@deschler We've been using 0.13-beta1 in production for a while now and it's all looking good.

Could it get a full 0.13 release for Django 2.0 please?
