### ISSUE TITLE
Support for Python 3.6 and Django 1.11

### ISSUE THREAD

**Issue by basitsattar** [deschler/django-modeltranslation#460]
Hi,
I am trying to use this package with python version 3.6 and django version 1.1 and pip install gives me version 0.12.2 while the documentation site mentions that 0.13+ should be installed. Can you please confirm if it'll work with django 1.1 or how can I install 0.13+ version and is that stable?

**Comment by dmarcelino** [comment]
Hi @basitsattar, `0.12.2` is compatible with Django 1.11. `0.13` is aimed at Django 2.0 and is still under development. See https://github.com/deschler/django-modeltranslation/issues/436#issuecomment-361912496 for more details.

**Comment by mvdklip** [comment]
The requirements table at http://django-modeltranslation.readthedocs.io/en/latest/installation.html doesn't mention 0.12.2 for Django 1.11.
