### ISSUE TITLE
NotRegistered: The model "Permission" is not registered for translation

### ISSUE THREAD

**Issue by karolyi** [deschler/django-modeltranslation#467]
After spending ~8hrs of time figuring out the problem, and after a nonsensical pull request, I can report I've found an issue:

I have a translated `InheritedPermission` model inherited from django's `Permission`, on which I use some translated fields.

When accessing the `Permission` with `has_perm` from the user angle, modeltranslation explodes. Probable cause is the `Permission.objects` manager gets replaced after expiring the relations cache, which can happen on various occasions (at my project it happens at initialization time).

I've created a test in my fork that reproduces the bug: see #466 and the latest failing commit.

@deschler, can we get a quick fix and a release? modeltranslation not being released for Django 2.x is the biggest blocker for me from changing to Django 2.

**Comment by gabn88** [comment]
This seams like the same issue I'm having. Something has changed with the managers between 0.12 and 0.13 that does not work well.

**Comment by last-partizan** [comment]
Hey, @karolyi what error do you get?

I'm getting
`modeltranslation.translator.NotRegistered: The model "Permission" is not registered for translation                                `

with django 2.1 and tests passing with 1.11

**Comment by karolyi** [comment]
Honestly, it was such a long time ago that I didn't remember. If you look at travis logs from my PR, you'll see exactly that error message.

I checked out the repo again, and it provide the same on my local dev. Although like I said, it was a long time ago, but the problem might lie on the `_expire_cache()`, which happens at init time.

**Comment by karolyi** [comment]
Btw, are you the new maintainer to the repo? What's happened with @deschler ?

**Comment by last-partizan** [comment]
Yeah, i'm new maintainer. @deschler is fine but don't have time for this, so he granted me access.

**Comment by last-partizan** [comment]
For me it looks like Permission using MultilingualQuerySet, but it should not.

**Comment by karolyi** [comment]
Thanks, I'm sure the community is grateful for your efforts. I too almost come to the point where I would have some time to look into the bug, but I'm still busy with something else. Maybe in a couple weeks tough, but I think you'll be faster than that.

As for the `MultilingualQuerySet`, yes, that might be a problem. :) All I can say right now is the realization I came to in https://github.com/deschler/django-modeltranslation/issues/467#issue-320650651.

**Comment by last-partizan** [comment]
Yeah, it's definitely MultilingualQuerySet.

I just checked tests with django-1.11, and there is normal QuerySet.

**Comment by karolyi** [comment]
Go @last-partizan, we all cheer for you :)

**Comment by last-partizan** [comment]
Note for self, and anyone who want to dig this bug:
```
t=modeltranslation.tests.tests.InheritedPermissionTestCase
tox -e py37-2.1 $t
...
add_manager tests.InheritedPermission
 bases: [<class 'modeltranslation.tests.models.InheritedPermission'>, <class 'django.contrib.auth.models.Permission'>]
  1 patch_manager_class auth.Permission.objects
  2 patch_manager_class tests.InheritedPermission._base_manager


tox -e py37-1.11 $t
...
add_manager tests.InheritedPermission
 bases: [<class 'modeltranslation.tests.models.InheritedPermission'>, <class 'django.contrib.auth.models.Permission'>]
  1 patch_manager_class tests.InheritedPermission.objects
  2 patch_manager_class tests.InheritedPermission._base_manager

```

In django 2 `auth.Permission.objects` gets patched instead of `tests.InheritedPermission.objects`.

Right now i don't know how to fix it, will investigate later.

**Comment by last-partizan** [comment]
@felixxm, @zlorf hey guys, can you take a look at https://github.com/deschler/django-modeltranslation/blob/master/modeltranslation/translator.py#L206

and maybe give some tips, how can i patch `tests.InheritedPermission.objects` in django-2. I tried to use model._meta.managers, and it patches right managers, but breaks a lot more.

**Comment by last-partizan** [comment]
Looks like i fixed issue by making patched managers local to the translated model.

Will release beta3 soon.

**Comment by felixxm** [comment]
@last-partizan That's great :rocket: I was going to take a look today.

**Comment by last-partizan** [comment]
@felixxm take a look anyway :) my fix is working, and did not break any tests, but maybe you have better idea.
