### ISSUE TITLE
object not saved on non-visible objects when upgrading from 0.12.1 to latest master (0.13b)

### ISSUE THREAD

**Issue by gabn88** [deschler/django-modeltranslation#471]
I have a model with soft deletes, which I don't want to show by default, so I have two Managers on the Model:

```
objects_with_hidden = IncludeHiddenObjects()
objects = NormalManager()

```
Before this used to work fine, but when upgrading to the latest master of modeltranslation the model does not get saved correctly. The funny things is that the models that are not hidden (so visible by MyModel.objects) are saved correctly...
In my save method I have:

```
def save(self, *args, **kwargs):
    super(MyModel, self).save(*args, **kwargs)
    self.set_roles(self)  # In this method I assume the model is saved, but it isn't after upgrading
```
This is a bug that should be fixed before releasing the last master to PyPy I think :)

EDIT: Maybe related, after upgrading, a migration was added AlterModelManager that includes a list of both managers. After downgrading again a migrations was made with AlterModelManager that only included the default (because higher on the list) IncludeHiddenObjects Manager.

**Comment by gabn88** [comment]
I'm still figuring out what is happening and why it goes wrong. Maybe someone can help me?

For completeness both managers are shown below:
```

class NormalManager(models.Manager):
    def get_queryset(self):
        ''' Includes the hidden filter '''
        return NormalQuerySet(self.model, using=self._db).filter(hidden=False)
    
class IncludeHiddenObjects(NormalManager):           # Thanks to inheritance all custom definitions stay.
    def get_queryset(self):
        '''
        Now without the hidden filter
        '''
        return NormalQuerySet(self.model, using=self._db)
```

**Comment by last-partizan** [comment]
@gabn88 Hi

Can you edit my test-case from https://github.com/deschler/django-modeltranslation/commit/dbf328997b3c825bca8c4d3972c94e7185639efe to make it fail?

**Comment by gabn88** [comment]
It seems to me the test is correct (y)

**Comment by last-partizan** [comment]
If test is correct, current master and released version should work fine with your code. Please check.

**Comment by mes3yd** [comment]
Is duplicate of https://github.com/deschler/django-modeltranslation/issues/455 and that has the root cause.

**Comment by gabn88** [comment]
Definitely, thanks for pointing it out @mes3yd
