### ISSUE TITLE
get_fields() is not called by TranslationAdmin

### ISSUE THREAD

**Issue by akxlr** [deschler/django-modeltranslation#473]
To make the Django admin only display a subset of model fields, sometimes it's useful to override `ModelAdmin.get_fields()`(which returns a list of fields) instead of just hardcoding `fields = [...]`. For example, if the set of admin fields depends on the object dynamically in some way.

This works when inheriting from the builtin `admin.ModelAdmin`, but `TranslationAdmin` does not seem to ever call `get_fields()`. Instead, the admin page just continues to show all fields.

```
class MyModelAdmin(TranslationAdmin):

    fields = ['foo', 'bar']  # Works

    def get_fields(self, request, obj=None):
        return ['foo', 'bar']  # Doesn't work, get_fields is never called
```

**Comment by bstar77** [comment]
Hi, is there any update on the issue? I have the same problem - I can not dynamically set the fields. get_fields is never called. 

Thank you for an update.

**Comment by jwindhager** [comment]
Same issue here. Trying to use TranslationInlineModelAdmin together with https://github.com/escaped/django-inline-actions, but it doesn't work as django-modeltranslation doesn't respect get_fields/get_readonly_fields.

**Comment by last-partizan** [comment]
Hi, yeah it still uses declared_fieldsets under the hood.

If someone have time to update it, i will gladly accept pull-request.

**Comment by chubz** [comment]
Just a quick note ... how would you approach this?

One way I see is to just trigger get_fields in the return on line 44 in the admin.py
There is a check there :
```
elif self.fields:
    # return [(None, {'fields': self.replace_orig_field(self.fields)})]
    # replace with
    return [(None, {'fields': self.replace_orig_field(self.get_fields())})]
```  
It seems like a small change that would just trigger the needed method?
If this is okay then I'll submit a PR.

**Comment by last-partizan** [comment]
@chubz probably declared_fieldsets is a legacy from old django, it's better take a look at new versions and update code accordingly (and replace declared_fieldsets with whatever is used in new django).

**Comment by elya5** [comment]
For me, `get_fields` is not getting called (modeltranslation version 0.18.11). After diggnig around a bit, it seems that `_get_declared_fieldsets` returns `None` and not the fields in accordance with `get_fields`.

**Comment by last-partizan** [comment]
If you can reproduce it in tests, please create PR with added test and fix.

**Comment by elya5** [comment]
[This test](https://github.com/elya5/django-modeltranslation/commit/5ceb7006e7f7519ab46f24374fc4fbece20623fc) demonstrates the problem. However, I am not sure how to fix it or what the source of the error is.

**Comment by bstar77** [comment]
We encounter the same problem here.

**Comment by Abhishek-Khanduri** [comment]
I was encountering the same issue but after upgrading the django-modeltranslation to `0.18.11`, it worked fine for me.
