### ISSUE TITLE
"Add another inline" is broken

### ISSUE THREAD

**Issue by ubeerli** [deschler/django-modeltranslation#475]
Hi @deschler 

First thanks for your very useful package :-) I'm using Django 1.11 with modeltranslation 0.13b1 (and tried with 0.12.2 as well). When I use a tabular inline with tabbed translated fields, they are gone for the new rows which I add through "add another line". Existing rows are successfully "moved" by the javascript function `createTabs()` but not the new lines (they are "recursively" added instead of appended, see screenshot, which I believe are copied by django, so the `td` to `div` change is not needed for the new lines).

![image](https://user-images.githubusercontent.com/22935734/44945850-62233c00-adf1-11e8-8954-865ae462d2c9.png)

This is how it should look like:
![image](https://user-images.githubusercontent.com/22935734/44945880-bfb78880-adf1-11e8-930a-a42fb964fff5.png)

Thanks!

**Comment by fabiocaccamo** [comment]
@deschler any update about this issue?

I just experienced it using `Django==2.1.7` and `django-modeltranslation==0.13`

**Comment by last-partizan** [comment]
@fabiocaccamo hey, i'm now responsible for maintaining this project but i don't have time right now to look into this issue.

You can try to fix it yourself and make pull-request.

**Comment by fabiocaccamo** [comment]
@last-partizan have you looked into this issue? If you have not time at all, please consider to move this project to https://github.com/jazzband

**Comment by last-partizan** [comment]
@fabiocaccamo I have some time, and just looked at issue. Can you install project from master and test if it works now?

**Comment by fabiocaccamo** [comment]
@last-partizan I installed the project from master and it works correctly, could you release a new version on `pypi`?

**Comment by last-partizan** [comment]
@fabiocaccamo Released.
