### ISSUE TITLE
When is the release version 0.13 (Support for Python 3.6 & Django 2.1)

### ISSUE THREAD

**Issue by dinhnghia** [deschler/django-modeltranslation#489]
Support for Python 3.6 & Django 2.1

**Comment by dmarcelino** [comment]
Quoting @nealtodd from https://github.com/deschler/django-modeltranslation/issues/457#issuecomment-426982461:

> @deschler We've been using 0.13-beta1 in production for a while now and it's all looking good.
> 
> Could it get a full 0.13 release for Django 2.0 please?


Can more people comment their experience with `0.13b1`?

**Comment by raratiru** [comment]
I have just found a useful guide for replacing django-modeltranslation with django-translated-fields:

https://github.com/matthiask/django-translated-fields/issues/7#issuecomment-457340307

**Comment by Pomax** [comment]
That is not an option for folks who rely on, say, [wagtail-modeltranslations](https://wagtail-modeltranslation-docs.readthedocs.io/en/latest/) @raratiru

**Comment by raratiru** [comment]
I understand, @Pomax .

Today something amazing happened, however. #476

**Comment by last-partizan** [comment]
Hi folks :)

I just joined project as a maintainer and working towards getting it released asap.

I hope we can see release on pypi in few days.

**Comment by Pomax** [comment]
Awesome, thanks @last-partizan!

**Comment by last-partizan** [comment]
Released 0.13-beta2 on pypi and added some issues to 0.13 milestone. Planning to release final version next tuesday.

**Comment by last-partizan** [comment]
Released 0.13-beta3 on pypi.

Please test it with your projects, especially if you have some unexpected model inheritance.
In previous versions we were patching `Manager()` in all parent models, now to fix #467 i'm making patched managers only for translated model. Probably it's right way to do it anyway, and hope in will not break something else.

Pushing final version release date to thursday (21 feb) if everything works fine.

**Comment by dmarcelino** [comment]
Wow, good stuff @last-partizan, it's good to see new life breath into this project! Keep up the good work!

**Comment by last-partizan** [comment]
Released 0.13 on pypi! :ok_man:
