### ISSUE TITLE
Not actually detected language on detail view.

### ISSUE THREAD

**Issue by bboyadao** [deschler/django-modeltranslation#491]
i used get_object_or_404 to show detail's post.
i pin set_lang form to navbar. 

So in the detail views, i change language in navbar. it's redirect to this slug with language_code changed. But i got 404.
example: 
    in: localhost:8000/en/cat/school.
then i change language in navbar, it redirect to: localhost:8000/ja/cat/school.
so i got 404. how can i fix it. if this post not yet translated. how can i show original content. 
Thanks

**Comment by last-partizan** [comment]
Probably it should be `jp`, not `ja`
