### ISSUE TITLE
Disable auto population of original field from translation fields

### ISSUE THREAD

**Issue by Tom1204** [deschler/django-modeltranslation#495]
How to disable auto population original field from _en, _ru field values. For example:
`greeting, greeting_en, greeting_ru`, and when I am initializing greeting, it automatically populate from greeting_en or greeting_ru fields respectively as written in settings

**Comment by Tom1204** [comment]
Could somebody from contributors help me? What kind of solution can you advice?

**Comment by last-partizan** [comment]
Hello, i don't know how to disable this behaviour.

What exactly you want to do?

**Comment by Tom1204** [comment]
I want to keep and require original field for 1 language(for example english), then want to add russian language. In handling request I do not want to make request body look like `{greeting_en: '...', greeting_ru:'...', ...}`, or just simply {'greeting': '...', 'greeting_ru': '...'}.

**Comment by Tom1204** [comment]
However, I think, I can handle it programmatically easily using `source`.
