### ISSUE TITLE
AttributeError: 'tuple' object has no attribute '__module__'

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [deschler/django-modeltranslation#498]
This is what I get when I follow your steps up to registering the translation 

**translation.py**

```
from modeltranslation.translator import translator, TranslationOptions
from .models import GameCategory


class GameCategoryTranslationOptions(TranslationOptions):
    fields = ('name', 'status',)


translator.register(GameCategory, GameCategoryTranslationOptions)
```

Actual Error

```
 File "/usr/src/app/gametype/translation.py", line 10, in <module>
    translator.register(GameCategory, GameCategoryTranslationOptions)
  File "/usr/local/lib/python2.7/site-packages/modeltranslation/translator.py", line 425, in register
    self._register_single_model(model, opts)
  File "/usr/local/lib/python2.7/site-packages/modeltranslation/translator.py", line 455, in _register_single_model
    add_manager(model)
  File "/usr/local/lib/python2.7/site-packages/modeltranslation/translator.py", line 210, in add_manager
    patch_manager_class(current_manager)
  File "/usr/local/lib/python2.7/site-packages/modeltranslation/translator.py", line 180, in patch_manager_class
    MultilingualQuerysetManager):
  File "/usr/local/lib/python2.7/site-packages/modeltranslation/translator.py", line 181, in NewMultilingualManager
    _old_module = manager.__module__
AttributeError: 'tuple' object has no attribute '__module__'
```

My django is 1.9.2 and my python is 2.7.13. Even though I try 2.7.11 this still occurs. Take note that I am in a containerized docker environment

**Comment by last-partizan** [comment]
Are your file named `translate.py` instead of `translation.py`?

**Comment by Dean-Christian-Armada** [comment]
@last-partizan .. Oh sorry I just edited my filename. The actual name is `translation.py`

**Comment by last-partizan** [comment]
Looks like it must be working. Same way we registering models in tests, and it works.

You can try to dig with ipdb, and look at  `manager` at `translator.py line 181`.

Can you show me your model?

**Comment by Dean-Christian-Armada** [comment]
Below logs is what I got 

```
print('===Manager Module===')
print(manager)

===Manager Module===
(24, <django.db.models.manager.Manager object at 0x7f8582c7e710>, False)
```

**Comment by last-partizan** [comment]
And what's in `GameCategory._meta.managers`?

**Comment by Dean-Christian-Armada** [comment]
Below is what I got

```
$ python manage.py shell
>>> from xxxx.models import GameCategory
>>> x = GameCategory._meta.managers
>>> x
[(24, <django.db.models.manager.Manager object at 0x7f77a65e4e10>, False)]
```

**Comment by last-partizan** [comment]
Oh, i just noticed you're using `django 1.9.2`, and latest version of modeltranslation does not support it.

You can try 0.11 or 0.12.

**Comment by Dean-Christian-Armada** [comment]
Nice! It's working now, thanks! I used 0.12

**Comment by Dean-Christian-Armada** [comment]
I just noticed that my name attribute value of my existing models suddenly became `null` when I tried to `$ python manage.py makemigrations && python manage.py migrate`

**Comment by last-partizan** [comment]
Probably new fields is not populated with translations yet?

modeltranslation tries to substitute current language into `name` from `name_LANGCODE`

**Comment by Dean-Christian-Armada** [comment]
<img width="526" alt="Ảnh chụp Màn hình 2019-03-15 lúc 18 10 19" src="https://user-images.githubusercontent.com/9837087/54424335-a3f05000-474d-11e9-94dd-7015bda4b75c.png">

I am talking about the photo above. The **Name** used to have a value before I migrate

**Comment by last-partizan** [comment]
Try to use TranslationAdmin instead of default django ModelAdmin.

**Comment by Dean-Christian-Armada** [comment]
```
 File "/usr/src/app/gametype/admin.py", line 109, in <module>
    admin.site.register(GameCategory, GameCategoryAdmin)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 107, in register
    admin_obj = admin_class(model, self)
  File "/usr/local/lib/python2.7/site-packages/modeltranslation/admin.py", line 250, in __init__
    super(TranslationAdmin, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/modeltranslation/admin.py", line 34, in __init__
    self.trans_opts = translator.get_options_for_model(self.model)
  File "/usr/local/lib/python2.7/site-packages/modeltranslation/translator.py", line 621, in get_options_for_model
    'translation' % model.__name__)
NotRegistered: The model "GameCategory" is not registered for translation
```

Error above showed up w/ my **admin.py** below

```
from xxx.models import GameCategory
from modeltranslation.admin import TranslationAdmin

class GameCategoryAdmin(TranslationAdmin):
    list_display = ('name', 'status', 'icon', 'rank')

admin.site.register(GameCategory, GameCategoryAdmin)
```

**Comment by last-partizan** [comment]
I don't know why you're getting this error.

Can you update django to 1.11 and try with latest version of django-modeltranslation?

**Comment by Dean-Christian-Armada** [comment]
Oh sorry, our application is not compatible with django 1.11...

**Comment by last-partizan** [comment]
> NotRegistered: The model "GameCategory" is not registered for translation

Try to add modeltranslation before your app in settings.py.

**Comment by Dean-Christian-Armada** [comment]
I think I kinda get it now.. It did not really delete the data in the database.. But it mapped the field in one of the translations so you need to do `python manage.py update_translation_fields`
