### ISSUE TITLE
Question: How to use modeltranslation in signals ?

### ISSUE THREAD

**Issue by cedeber** [deschler/django-modeltranslation#501]
Hello. I am using modeltranslation on FileField and ImageField and I would like to delete unused files when a Model is deleted or updated. I am new to the Django world and I didn't find any info into the documentation. I am using the last version of Django. Thanks for the help.

**Comment by last-partizan** [comment]
Hi, i think it will be something like this:

```
def handle_delete(instance, **kwargs):
    instance.file.delete(save=False)
    instance.file_en.delete(save=False)
    instance.file_fr.delete(save=False)
```

**Comment by cedeber** [comment]
Thanks. Is there no kind of automatism to retrieve all the languages currently in use in the DB ?

**Comment by last-partizan** [comment]
No, there is no such thing.

**Comment by cedeber** [comment]
Ok, thanks for the help.
