### ISSUE TITLE
sync_translation_fields lost original field text

### ISSUE THREAD

**Issue by federicodv** [deschler/django-modeltranslation#505]
Hi, im not sure if this is a bug or a expected behavior  but .. let say i have this model:

class ModelX(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False, help_text=_("Type of Community"))

i create the translation file 
@register(ModelX)
class ModelXTranslationOptions(TranslationOptions):
    fields = ('name', )

but when i run makemigrations or sync_translation_fields, the fields are created .. thats ok but i lost the original text of the name field
maybe im missing something ?

btw: i seted up languajes and the defaults
LANGUAGES = (
    ('en', _('English')),
    ('pt', _('Portuguese')),
    ('es', _('Spanish')),
)
MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'
MODELTRANSLATION_PREPOPULATE_LANGUAGE = 'en'

django 2.1

**Comment by last-partizan** [comment]
Hi, it's expected behaviour.

Technically text is not lost, it's still in database, but now you have empty fields with translations and `obj.name` is translated to `obj.name_en` and name_en is empty.

You can access it by using something like `ModelX.objects.annotate(name_untranslated=F('name'))`
