### ISSUE TITLE
TabbedTranslationAdmin and django 2.2

### ISSUE THREAD

**Issue by liminspace** [deschler/django-modeltranslation#506]
TabbedTranslationAdmin doesn't work with django 2.2.
Version: 0.13

![Screenshot from 2019-04-14 15-57-51](https://user-images.githubusercontent.com/5173158/56093186-19c31500-5ece-11e9-93c7-d7fb07789425.png)

![Screenshot from 2019-04-14 16-08-27](https://user-images.githubusercontent.com/5173158/56093331-07e27180-5ed0-11e9-93ad-7ca4c1637b30.png)

**Comment by mrMarcosss** [comment]
yep, the same problem guys

**Comment by last-partizan** [comment]
Thanks for the reports.

Probably something changed in 2.2 and our js needs to be ajusted.
Unfortunately i don't have time to look into this, but gladly accept PR with fixed.

**Comment by last-partizan** [comment]
it was one-line fix. Released 0.13.1
