### ISSUE TITLE
Is it possible to register translated fields with a different max_length?

### ISSUE THREAD

**Issue by easherma** [deschler/django-modeltranslation#512]
Hello, 

Thanks all for your hard work on this project. 
I wasn't clear on this from the docs, but is there a way to register fields for translation while also defining different max_lengths for those fields? 

I.E. A description field in English might have a 255 character limit, but for Spanish we might want to have that same field have a higher limit, etc.

**Comment by last-partizan** [comment]
Hi
Looks like it does not supported.
