### ISSUE TITLE
Admin issue with manually imported object without default translation

### ISSUE THREAD

**Issue by thetractor** [deschler/django-modeltranslation#516]
Hi there,

I have four languages (DE, FR; IT, RM) enabled in my Django (2.2.3) configuration and Django Modeltranslation (0.13.3) running with full standard configuration.

```
LANGUAGES = (
    ("de", gettext("German")),
    ("fr", gettext("French")),
    ("it", gettext("Italian")),
    ("rm", gettext("Rumantsch")),
)

EXTRA_LANG_INFO = {
    'rm': {
        'bidi': False,  # right-to-left
        'code': 'rm',
        'name': 'Rumantsch',
        'name_local': u'Rumantsch',
    },
}

LANG_INFO = {**django.conf.locale.LANG_INFO, **EXTRA_LANG_INFO}
django.conf.locale.LANG_INFO = LANG_INFO
```
When I now import objects trough a management command (from a second DB connected to Django into the default DB) I run in to some problems.

Let's say I import an object into a Model with a translatable `title` field (Required) and this imported object only provides the French title. When I then open this object in the Django Admin the French field is filled in correctly but I can not save the object since the German field is a mandatory field. (Due to the `title` being a mandatory field and the standard behavior of setting the default language as a mandatory field).

So if I want to save that object I have to provide the German translation for this object. But in my case there is no such translation and the application will never need one.

What would be the correct way to import objects that have no German translated title so I can use the admin to edit such objects (without making the title field optional)?

This is how I import the objects:
```
Foo.objects.create(title_de='', title_fr='bar_fr', title_it='', title_rm='')
```

**Comment by last-partizan** [comment]
Probably you should put something in title_de, line "NOT_TRANSLATED".
