### ISSUE TITLE
Django 3.0 compatibilities

### ISSUE THREAD

**Issue by infosrabah** [deschler/django-modeltranslation#521]
Hi, as I was in need to use django 3.0 I did compile with it and get those error :
...
  File "/home/rico/.local/share/virtualenvs/bacony-G3NgZpUh/lib/python3.7/site-packages/modeltranslation/translator.py", line 5, in <module>
    from django.utils.six import with_metaclass
ModuleNotFoundError: No module named 'django.utils.six'
.....
Since 'django.utils.six' is deprecated in django 3.0
fixed it importing six python pacakge directly : 
import six

instead of from django.utils.six import with_metaclass
hope it's gonna fixed in the next 0.13.4.

**Comment by last-partizan** [comment]
Yes, it will be fixed. We have one pending pull-request.

Be careful, right now it has some tests broken, so with only import fixes it may not work as expected in some cases.

**Comment by infosrabah** [comment]
Thank's for hte reply, thought the project was dropped, LoL

waiting as hell for the fix,

thank you,

Amazing project.

**Comment by last-partizan** [comment]
@infosrabah pull-request is without activity for some time, it you really need this, you can take a look at in, fix whatever it has broken to pass the tests, and i'll merge it.

**Comment by last-partizan** [comment]
@infosrabah you can test your code with master branch now.

We'll release new version after Django 3.0 release somewhere in December.

**Comment by infosrabah** [comment]
Thank you
Hopefully gonna be 100% compatible for Django 3.0
