### ISSUE TITLE
extra tab lang switcher in stackedinline

### ISSUE THREAD

**Issue by olarcheveque** [deschler/django-modeltranslation#522]
django 2.0.5
django-modeltranslation 0.13.3

With inline model admin in stacked mode, when you click on "add another <modelname>", the generated inline got an extra language tab switcher.

[screenshot](https://prnt.sc/pi3m3f)

Note: there is no issue when I switch for TabularInline

**Comment by last-partizan** [comment]
Fixed and released patched version.
