### ISSUE TITLE
When I use create() method, origin field is copied into translation files automatically

### ISSUE THREAD

**Issue by llr114** [deschler/django-modeltranslation#547]
I would liket to set default words into "name" origin field.
But when I run it, "name" is copied into "name_ja" (ja is my default language)
Is there any option that I cancel autopopulate.

```python
#forms.py
def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.save()
	name = 'person_name_' + str(user.id)
	Person.objects.create(user=user, name=name) #here
```

```python
#models.py
class Person(models.Model):
	name = models.CharField(max_length=255)
	created_at = models.DateField(default=timezone.now)
	user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='person_user')
```

```python
#translatinon.py
class PersonTranslationOptions(TranslationOptions):
    fields = ('name',)
translator.register(Person, PersonTranslationOptions)
```

**Comment by last-partizan** [comment]
If ja is your default language, it is expected behaviour.

You could try `...create(name=name, name_ja="")`

**Comment by llr114** [comment]
It works! Thank you.

**Comment by llr114** [comment]
@last-partizan 
I am sorry but when I try this, the name also becomes to "".

**Comment by last-partizan** [comment]
@llr114 after you add modeltranslation, your `name` field will be dependent on current language.

If your language is Japanese, and `name_ja=""`, it is expected for name to be `""`.
