### ISSUE TITLE
FroalaField is not supported by modeltranslation

### ISSUE THREAD

**Issue by KamilRAliyev** [deschler/django-modeltranslation#548]
Dear team, I am using **frola editor** on my **django** project. Today I tried to write modeltranslations for my website. it throws error :
`django.core.exceptions.ImproperlyConfigured: FroalaField is not supported by modeltranslation.
`on command
`python manage.py makemigrations
`
Is there solution for this problem?

**Comment by last-partizan** [comment]
Take a look at source code raising this exception, maybe you can find a solution.

**Comment by KamilRAliyev** [comment]
How to add custom field to supported fields?
I've tried in **translation.py** filer:
`from froala_editor.fields import FroalaField
from .models import VisaServices, AboutUs, SiteSettings
from modeltranslation.fields import SUPPORTED_FIELDS
SUPPORTED_FIELDS += FroalaField
`
 but it throws error:
`django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: modeltranslation
`
on command:
`python manage.py makemigrations`

**Comment by last-partizan** [comment]
I don't know. Take a look at source code throwing exception, @KamilRAliyev
