### ISSUE TITLE
Translation of Coderedcms

### ISSUE THREAD

**Issue by milanmaximo** [deschler/django-modeltranslation#552]
I am trying to translate models in Coderedcms but all the time I got this error.
AttributeError: 'function' object has no attribute 'cache_clear' 

Does anyone know how to solve this issues?
Thanks a lot.

**Comment by mondeja** [comment]
Can you share the full traceback, please?

**Comment by milanmaximo** [comment]
@mondeja  Here is the latest line from terminal 
`AttributeError: 'function' object has no attribute 'cache_clear' `

I have follow all the steps regarding installation and setup model-translation, also I have creates transaltion.py but every time when I want to do makemigrations I got this error. 

I have create also two test pages separately from Coderedcms and its working, but when I want to translate models then I got that error.
I have trying to find some answers on Coderedcms but there is lack of inromations about models transaltion.

**Comment by last-partizan** [comment]
That's probably unrelated to modeltranslation.
