### ISSUE TITLE
Fallback doesn't work in QuerySet

### ISSUE THREAD

**Issue by pyutil** [deschler/django-modeltranslation#556]
I just want ask if the package should have the functionality described bellow or if this is not supported (fallback in queryset conditions).
I have found this
`https://stackoverflow.com/questions/27418377/django-modeltranslation-queries-fallback`
and it looks so that this functionality is not supported and I have ask like so:
`.filter(Q(title_de = 'hello') | Q(title_en = 'hello'))`
However problem is that it is difficult to know which fallback was used while reading the 'hello' value :(

------- so, description of the behaviour:

0.15, dj3, py3.8.

I have in db:
slug, slug_cs == 'horse-care'
slug_en, slug_de == null

With language "de" reading will return 'horse-care'; which I think behaves properly.
When I ask using QuerySet, `Category.objects.filter(slug='horse-care')` I will receive nothing.

Same happens without MODELTRANSLATION_FALLBACK_LANGUAGES
or with their different settings like:
```
MODELTRANSLATION_FALLBACK_LANGUAGES = ('cs',)
MODELTRANSLATION_FALLBACK_LANGUAGES = {
    'default': ('en', 'de', 'cs',),
    'pl': ('cs',),
}

```
More about the behaviour bellow.
Model is based on django-mptt, so .objects gives MultilingualTreeQuerySet.
I have added .objects2=models.QuerySet.as_manager() which gives standard MultilingualQuerySet.
However both are empty for language "de".
```
# objects2 = models.QuerySet.as_manager()
Category.objects2.get(pk=21).slug_de   # None but same behaviour if ==""
Category.objects2.get(pk=21).slug_cs
# 'horse-care'
Category.objects2.get(pk=21).slug
# 'horse-care'
Category.objects2.filter(slug_de__isnull=True, slug_cs='horse-care')
# <MultilingualQuerySet [<Category: Horse care>]>
Category.objects.filter(slug='horse-care')   # with language: de
# <MultilingualTreeQuerySet []>
Category.objects2.filter(slug='horse-care')   # with language: de
# <MultilingualQuerySet []>
```
queryset.query contains no fallback, just de language:
`SELECT "core_category"."id", "core_category"."slug", "core_category"."slug_cs", "core_category"."slug_en", "core_category"."slug_de", "core_category"."slug_pl",  "core_category"."lft", "core_category"."rght", "core_category"."tree_id", "core_category"."level" FROM "core_category" WHERE "core_category"."slug_de" = horse-care ORDER BY "core_category"."tree_id" ASC, "core_category"."lft" ASC`

**Comment by last-partizan** [comment]
looks like it doesn't supported.

**Comment by kunambi** [comment]
@last-partizan Our project has this requirement as well. 

Do you have any plans to implement this feature? Is there a way to monkey patch this?

**Comment by kunambi** [comment]
Hi @last-partizan, just bumping this thread. Any insight/response on this?

TYIA

**Comment by last-partizan** [comment]
@kunambi i think, it is better if filtering is using only current language.

Filtering by all languages is better left to application level, only where it's explicitly needed.
