### ISSUE TITLE
How to use the original queryset (raw, not patched)?

### ISSUE THREAD

**Issue by ppo** [deschler/django-modeltranslation#560]
Is there a way to use the original queryset (i.e. with the original field names, without renaming)?

I want to do this (cf. #286) in a `DetailView.get_object()`:

```
slug_field = build_localized_fieldname("slug", get_language())
raw_qs.filter(Q(**{slug_field: slug}) | Q(**{slug_field: None}, slug=slug))
```

**Comment by last-partizan** [comment]
There is no simple way AFAIK. Try to look at modeltranslation/translator.py. and maybe you can figure something out.

You can use chat for questions: https://gitter.im/django-modeltranslation/community
