### ISSUE TITLE
Version 0.15 not working with Django 3.0.8

### ISSUE THREAD

**Issue by dorb4r** [deschler/django-modeltranslation#561]
`FieldDoesNotExist` is now imported **only** from `django.core.exceptions`

So this line in `manager.py` causing a crash:
`from django.db.models import FieldDoesNotExist`

I saw a fix for this already merged to master:
[PR-553](https://github.com/deschler/django-modeltranslation/pull/553)

Please publish it so we can update our server to Django 3.0.8

**Comment by last-partizan** [comment]
Released 0.15.1
