### ISSUE TITLE
DRF: Serializing raises exception

### ISSUE THREAD

**Issue by Adman** [deschler/django-modeltranslation#564]
I'm trying to use djangorestframework to dynamically return model instances via ajax call. The final call looks like this:
```python
data = {
    'products': products,
}
return JsonResponse(data, status=200)
```
Each of the `product` instances contains two translated fields.
The aforementioned `JsonResponse` call raises
```
/lib/python3.8/site-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MultilingualQuerySet is not JSON serializable
```

Is there any workaround for this? I have notice [this mixin](https://github.com/deschler/django-modeltranslation/issues/407) but that doesn't work either.

Package versions:
django 3.0.9
drf 3.11.1
django-modeltranslation 0.15.1

**Comment by last-partizan** [comment]
JsonReponse looks like part of Django, and not djangorestframework. In DRF we use Response.

And models does not serialized directly, you need to define serializer and use it to produce data.
