### ISSUE TITLE
Inline item, addition broken

### ISSUE THREAD

**Issue by VDShark** [deschler/django-modeltranslation#565]
Tabs don't applied to new inlines.
It worked in 0.14, but since 0.15 broken.

![image](https://user-images.githubusercontent.com/8749506/90495679-92cf1e00-e14d-11ea-9d4b-556dc6f164d2.png)

![image](https://user-images.githubusercontent.com/8749506/90495714-9b275900-e14d-11ea-9aa7-8d3351ab557f.png)

**Comment by last-partizan** [comment]
Please check if it's working in 0.16.2

**Comment by VDShark** [comment]
Yes, it works.
Thanks :)
