### ISSUE TITLE
Using modeltranslation causes Django to create same migrations repeatedly for custom User model

### ISSUE THREAD

**Issue by someq** [deschler/django-modeltranslation#566]
Hello!

I have a custom User model defined like this:

```
class User(AbstractUser):
    ... # fields
```

User has default objects manager inherited from Django's AbstractUser.

And inherited SpecificUser model with some custom managers like this:

```
class SpecificUser(User):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    ... # other fields

    active = ActiveManager()
    deleted = DeleteManager()
```

It all worked fine but there's an issue. First: User has no fields for translation and SpecificUser has some. But I still had to setup TranslationOptions for User with empty fields like this:

```
@register(User)
class UserTranslationOptions(TranslationOptions):
    fields = tuple()
```

As it threw me an error otherwise. Though can not reproduce it now even after removing TranslationOptions for User, probably due to migrations applied.

Second one is that django creates migrations for these models every time when I call makemigrations command even if there were no changes in models:

```
(venv) ...$ ./manage.py makemigrations
Migrations for 'core':
  core/migrations/0068_auto_20200819_0952.py
    - Change managers on user
Migrations for 'app':
  app/migrations/0063_auto_20200819_0952.py
    - Change managers on specificuser
(venv) ...$ ./manage.py makemigrations
Migrations for 'core':
  core/migrations/0069_auto_20200819_0953.py
    - Change managers on user
Migrations for 'app':
  app/migrations/0064_auto_20200819_0953.py
    - Change managers on specificuser
```

Migrations are all the same having single operation which replaces default manager with itself:

```
migrations.AlterModelManagers(
    name='doctor',
    managers=[
        ('objects', django.contrib.auth.models.UserManager()),
    ],
),
```

It appears with or without custom managers on SpecificUser model. I think this has something to do with patching managers by modeltranslations app, but appears only on these two models. Also this did not appear before I started using modeltranslations.

Can this be fixed or bypassed somehow? Any help would be appreciated.

**Comment by last-partizan** [comment]
Try to specify default manager, before your custom managers. `objects = models.Manager()`.

**Comment by someq** [comment]
> Try to specify default manager, before your custom managers. `objects = models.Manager()`.

Thanks, it works with default `models.Manager()`, but those are User models, and Django provides another manager for them - `django.contrib.auth.models.UserManager` - and it does not work with it.

**Comment by last-partizan** [comment]
Oh, now i understand.

Probably there is no easy workaround, but you can try to fix it and make pull-request.

**Comment by someq** [comment]
Ok, thanks. I'll try it some time, and write here if I come with any fixes.

**Comment by someq** [comment]
Closed till the better times when I have time and will to fix it.
