### ISSUE TITLE
Autopopulation not working with Wagtail

### ISSUE THREAD

**Issue by urlsangel** [deschler/django-modeltranslation#568]
I'm using `django-modeltranslation` with Wagtail - I'm not using `wagtail-modeltranslation` as I only want to target non-page models, for which I'm using `wagtailtrans` for synchronised trees.

My installed versions are:

```
Django==3.1
django-modeltranslation==0.15.1
wagtail==2.10
```

The autopopulation functionality doesn't work when saving a Wagtail snippet (subclassed from a plain Django Model) - I'm using this setting:

`MODELTRANSLATION_AUTO_POPULATE  = True`

To work around this, I've added a Django signal receiever to call the `update_translation_fields` fields command on `post_save`, however this only works with the latest update that includes a `--language` flag. I can then loop through the non-default languages and update the model that has been saved.

This [latest feature](https://github.com/deschler/django-modeltranslation/commit/ac91740a5c3d718b8695514da8a0dd7b90aa1ee6) has not been released to PYPI yet, so I've cloned the code to my local set up - do you know if this feature will be released and can be relied on for a production environment within the next few weeks?

**Comment by last-partizan** [comment]
Released 0.15.2
