### ISSUE TITLE
What does base-class approach mean in the documentation?

### ISSUE THREAD

**Issue by aranmohyeddin** [deschler/django-modeltranslation#579]
I'm referring to [here](https://github.com/deschler/django-modeltranslation/blame/master/docs/modeltranslation/registration.rst#L150)

**Comment by last-partizan** [comment]
https://gitter.im/django-modeltranslation/community?at=60000c60d5f4bf2965e65c65

Please use chat for questions.

**Comment by aranmohyeddin** [comment]
I can't find `TranslatableModel` in the [whole repo](https://github.com/deschler/django-modeltranslation/search?q=TranslatableModel) or the documentation. Is there any documentation or example for this?

**Comment by last-partizan** [comment]
@aranmohyeddin becouse we don't use it. We use registration approach.

**Comment by aranmohyeddin** [comment]
Can you please give me some link so that I will understand what it is and how I can use it with this package?

**Comment by last-partizan** [comment]
@aranmohyeddin you can't use base-model approach with this package, becouse it uses registration approach.

Take a look at this for example: https://pypi.org/project/django-translations/, this is base-model approach.
