### ISSUE TITLE
MultiLanguage form

### ISSUE THREAD

**Issue by paulwinex** [deschler/django-modeltranslation#581]
I think multi language form is very useful! Same as in admin but for generic templates.
I was maked custom frontend admin pages and i need to give site admins create post on different languages on same page.
This is pseudo code example for multi lang form

```
<form action="" method="post">
    {% csrf_token %}
    {% for lang, fields in form.translated_fields.items %}
        <h4>{{lang}}</h4>
        {% for field in fields %}
            {{ field.label_tag }}<br>
            {{ field }} <br>
        {% endfor %}
    {% endfor %}
    <hr>
    {% for field in form.non_translated_fields %}
        {{ field.label_tag }}<br>
        {{ field }} <br>
    {% endfor %}
    <br>
    <button>Add Post</button>
</form>
```
It would be great to add functionality like this to TranslationModelForm class!

**Comment by last-partizan** [comment]
We already have multilang form for admins, closing this.
