### ISSUE TITLE
Custom DRF serializer support

### ISSUE THREAD

**Issue by iriptheskin** [deschler/django-modeltranslation#585]
Hi, I've developed some solution for DRF that allows you automatically return the needed field with the language set in the query params. It's only a draft but I would like to make it a part of this library. So, the idea looks like the following:

# serializers.py
```python
from modeltranslation.serializers import TranslationSerializer

class ArticleSerializer(TranlsationSerializer):
     class Meta:
           model = Article
```

# settings.py 
```TRANLSATION_QUERY_PARAM='lang'```

And under the hood, it does autogeneration for each translated field of `SerializerMethodField`.

By the way, I don't have implementation yet for the nested serializers case but can be implemented in the future.

If you are interested, I can create a PR with code changes. Thanks.

**Comment by iriptheskin** [comment]
I've seen other issues, so it could be implemented as a mixin I guess to be independent of the DRF library.

**Comment by last-partizan** [comment]
@iriptheskin what are your use-case? do you need to make queries in different languages?

as i see it - translation better be independent from DRF.

**Comment by iriptheskin** [comment]
@last-partizan 
My case:

Simple shop. It has shop description information (~20 pages/models) and lots of products, categories, properties, etc.
All it needs to be available in several languages. So, I developed the way of `SerializerMethodField` that defines the field depending on the language parameter. But for so many models it seems unreal.

Then I developed a new approach that allows you to use inheritance from upgraded serializer and custom serializer fields to have these translations automatically set without copying the logic. It's okay to me, but I would like to improve this version to do it only with inheritance or mixing with autogenerated serializer method fields. 

As the result, to achieve the translation you can basically use the code I sent above. 

What do you think? Or there exists better approach?

**Comment by last-partizan** [comment]
Yes, you follow this steps: https://docs.djangoproject.com/en/3.1/topics/i18n/translation/

- enable LocaleMiddleware
- add view to switch language

(you don't have to use django views/middleware, you can customize it for your needs)

After that, just use normal serializers and switch language, your serializers will be using selected language automatically.

**Comment by iriptheskin** [comment]
@iriptheskin It means I can set a language once via post request and then use normal api without any customization?

**Comment by last-partizan** [comment]
@iriptheskin Yes
