### ISSUE TITLE
Question - unicity constraint of translations

### ISSUE THREAD

**Issue by lc-thomas** [deschler/django-modeltranslation#589]
Hello,

It seems that if a **unique** CharField is translated then its "_en" "_de" "_fr" variants will all have the "unique" constraint as well.

 That's a problem for me because I need a unique field but with translations that could be repeated.
 
Ex for a model "Item" I'd like to have rows like :

```
+-------+---------+---------+
| name  | name_en | name_fr |
+-------+---------+---------+
| table | table   | table   |
| chair | chair   | chaise  |
+-------+---------+---------+
 ```

That is, unique name, but not unique name_en and name_fr 
 
I thought I could do that with **TranslationOptions** but I have no luck yet. How can I do this ?

**Comment by last-partizan** [comment]
translations can be repeated, as long as they're unique for their field.

uniqueness is per column, not per row.

so you can have what you want, if i understood you correctly.

But, if you want this:

```
+-------+---------+---------+
| name  | name_en | name_fr |
+-------+---------+---------+
| table | table   | table   |
| chair | table   | chaise  |
+-------+---------+---------+
```

Then you should use unique for `name`, and add `translated_name`, without unique constraint, so you will have this:


```
+-------+---------+---------+
| name  | translated_name_en | translated_name_fr |
+-------+---------+---------+
| table | table   | table   |
| chair | table   | chaise  |
+-------+---------+---------+
```
