### ISSUE TITLE
Tagging main select with a css class

### ISSUE THREAD

**Issue by hovi** [deschler/django-modeltranslation#602]
Main language `select` switch created here:

https://github.com/deschler/django-modeltranslation/blob/master/modeltranslation/static/modeltranslation/js/tabbed_translation_fields.js#L443

Is plain `select` element with no class or wrapper. It is hard to select (in terms of css selectors) it using css. Would be nice to add specific class or a another mechanism for styling purposes.

**Comment by last-partizan** [comment]
Please, make a PR with this change.

let's call it `id="modeltranslation-main-switch"`

**Comment by last-partizan** [comment]
Released new version with your patch
