### ISSUE TITLE
makemigrations is creating migrations for the new translation fields.

### ISSUE THREAD

**Issue by Simouche** [deschler/django-modeltranslation#603]
we started using modelstranslation in an already running project.
we followed the setup in the docs, used "sync_translation_fields" command manually.
but now, when we run "manage.py makemigrations", django create a migration for the translation fields that are already synced with the "sync_translation_fields" command.

```Migrations for 'mainapp':
  mainapp\migrations\0179_auto_20210623_0854.py
    - Add field presentation_en to adrestorerpresentation
    - Add field presentation_fr to adrestorerpresentation
    - Add field title_en to adrestorerpresentation
    - Add field title_fr to adrestorerpresentation
    - Add field name_en to allergen
    - Add field name_fr to allergen
    - Add field name_en to dayplate
    - Add field name_fr to dayplate
    - Add field type_en to dishtype
    - Add field type_fr to dishtype
    - Add field description_en to foodsection
    - Add field description_fr to foodsection
    - Add field name_en to foodsection
    - Add field name_fr to foodsection
    - Add field name_en to ingredient
    - Add field name_fr to ingredient
    - Add field kitchen_name_en to kitchentype
    - Add field kitchen_name_fr to kitchentype
    - Add field description_en to plate
    - Add field description_fr to plate
    - Add field name_en to plate
    - Add field name_fr to plate
    - Add field description_en to provideroffersfood
    - Add field description_fr to provideroffersfood
```

is this normal? will it cause any issues? we didn't migrate the new migrations yet to avoid conflicts in the db.

**Comment by last-partizan** [comment]
You should use sync_translation_fields or migrations, not both.

**Comment by Simouche** [comment]
I used sync_translation_fields, and the fields are present in my db schema! even so, when i run makemigrations is suggests creating the fields again.

here:
```
python manage.py sync_translation_fields
No new translatable fields detected
```

**Comment by last-partizan** [comment]
Yes, sync_translation_fields does not update migration history. It should be used only in environment with no migrations.

**Comment by Simouche** [comment]
the possibility of using makemigrations without South, is not mentionned in the docs. i didn't even know that this can work with normal makemigrations.
just to confirm, modeltranslations can work normally with simple "makemigrations", right?

**Comment by last-partizan** [comment]
Yes, it should work normally.
