### ISSUE TITLE
how to use in the DRF?

### ISSUE THREAD

**Issue by spavlovich001** [deschler/django-modeltranslation#612]
```python
def get_queryset(self):
     return Some.objects.all()
```

```python
def list():
  translation.activate('de')
```    
but I have all fields in queryset. How to get only _de fields(field, who translated) and all field without translate?

**Comment by spavlovich001** [comment]
2. If I push queryset to DRF serializer, djangorest say: error, multilanguage queryset, but list of dict needed. Convert queryset to list of dict --> did not work

**Comment by last-partizan** [comment]
Use chat for questions.
