### ISSUE TITLE
JSONField not supported even though it's now a core Django field

### ISSUE THREAD

**Issue by parruc** [deschler/django-modeltranslation#614]
JSONField is an officially supported django field included into django.db.models since Django 3.1 but looks like it does not work well with modeltranslation ATM.
I tried adding it to MODELTRANSLATION_CUSTOM_FIELDS as an older issue suggested but it does not seem to work.

In admin area when I try to save the objects I get a:
   "Please correct the error below."

It's also not included in fields compatibility matrix in the documentation.

**Comment by parruc** [comment]
My bad the field giving error was another, buildtin JSONField seems to work correctly. 

I would keep it open to remember to proudly add it  to the compatibility matrix.
It could also be included in the fields that works out of the box without

**Comment by ruchika2012** [comment]
Hey! could you please share the code, how did you used the JSON field in modelTranslation?

**Comment by parruc** [comment]
There is no code needed, just add JSONField  to the MODELTRANSLATION_CUSTOM_FIELDS in settings.py

**Comment by ruchika2012** [comment]
> 

Thank you so much for responding.
