### ISSUE TITLE
update_translation_fields populates Null values in JSON field

### ISSUE THREAD

**Issue by hunytalk** [deschler/django-modeltranslation#615]
I'm using django-modeltranslation for a JSONField in django model and when i try and run `update_translation_fields` management command for initializing default translation fields, i get NULL values in fields.
This management command is working fine with other text like fields ( in a different model, CharField etc ) and also fixture data for same JSON field is working fine as well but doesn't seem to copy existing data in any of my dev environment.
I'm getting info message `Updating data of model <Model Name>` and no error.

**Comment by last-partizan** [comment]
Hi

You can add custom migration, or you can debug this issue, find out why it doesn't work and create PR.

**Comment by ruchika2012** [comment]
> I'm using django-modeltranslation for a JSONField in django model and when i try and run `update_translation_fields` management command for initializing default translation fields, i get NULL values in fields. This management command is working fine with other text like fields ( in a different model, CharField etc ) and also fixture data for same JSON field is working fine as well but doesn't seem to copy existing data in any of my dev environment. I'm getting info message `Updating data of model <Model Name>` and no error.

I am also facing the same issue, did you got something?

**Comment by ruchika2012** [comment]
> Hi
> 
> You can add custom migration, or you can debug this issue, find out why it doesn't work and create PR.

Hey, could you please elaborate how to add custom migration? Or if there's a better solution?

**Comment by last-partizan** [comment]
https://docs.djangoproject.com/en/4.1/topics/migrations/#data-migrations

Here's Django docs on data migrations. You can filter fields with Null values and replace it with whatever you need.
