### ISSUE TITLE
mypy support of translated fields

### ISSUE THREAD

**Issue by ppeczek** [deschler/django-modeltranslation#622]
Well, I'm probably doing something wrong, but I integrated `django-modeltranslation` into my project long ago and could have missed something.

When I run today `mypy .` I get `error: "Tournament" has no attribute "name_en"`, because I am accessing the `self.name_en` field: `self.slug = slugify(self.name_en)`. Well, I do not define translated fields by myself in models, I supposed that those fields are added magically into the models.

If this page is actual:
https://django-modeltranslation.readthedocs.io/en/latest/usage.html#accessing-translated-and-translation-fields
and if I understand correctly then every translated field should be appended to models after `python manage.py update_translation_fields`, but I only get some logs:
```
Using default language: en
Working on models: ...
Updating data of model '<class '...'>'
Updating data of model '<class '...'>'
Updating data of model '<class '...'>'
Updating data of model '<class '...'>'
```
and there are no changes in the models.

After manual adding fields with postfix `_{lang}` I get the error: `ValueError: Error adding translation field. Model '...' already contains a field named 'name_en'.` and when I'm getting into the source code, then it seems like those lines shouldn't be appended into my model, but should be "created" on the run. If so, then the docs are out of date and I suppose mypy should always fail.

BTW thank you for your work. You've done a great job!

**Comment by last-partizan** [comment]
Hello, you are right, django-modeltranslation automatically adds fields for all languages.

But there is no way to tell type checker about it.

I think, you have two options:

Instead of using fields dorectly, doing this:

```python
with translation.override("en"):
    self.slug = slugify(self.name)
```

Or use `getattr`.

Or, maybe even write mypy plugin, which will add fields for translated languages to model.

**Comment by last-partizan** [comment]
And `update_translation_fields` not adding anything to models, it is doing this:

> Updates empty values of translation fields using values from original fields (in all translated models).

**Comment by ppeczek** [comment]
Thank you for your answer!

I think this is a good idea to implement the addition of the new fields to the model. I suppose I should fork this project or propose a pull request. 

I believe that the main part that should be modified is `translator.py:158`, part of `add_translation_fields`:
```python3
            # Check if the model already has a field by that name

            if hasattr(model, localized_field_name):
                # Check if are not dealing with abstract field inherited.
                for cls in model.__mro__:
                    if hasattr(cls, '_meta') and cls.__dict__.get(localized_field_name, None):
                        cls_opts = translator._get_options_for_model(cls)
                        if not cls._meta.abstract or field_name not in cls_opts.local_fields:
                            raise ValueError("Error adding translation field. Model '%s' already"
                                             " contains a field named '%s'." %
                                             (model._meta.object_name, localized_field_name))
```
so the error would not be thrown if the field is "redefined", but if the "redefinition" differs from what is generated by the `django-modeltranslation`. This might be a little more complex, because if I see correctly, then the only thing passed here is a list of fields names' to be checked.

The other part of the pull request could be a management command that generates the fields in the user's code, but there is a catch here: if the fields are generated, then if user would try to modify them and get an error then it would feel like a malfunction :thinking: 
To avoid that the whole validation should be removed. Maybe if the field is defined explicitly then user agrees to override the `django-modeltranslation` field? :shrug:

**Comment by last-partizan** [comment]
Fields like `name_en` meant to be dynamic, and not supposed to live in user code.

If you want mypy to correctly recognize it, we need to write something like this: https://github.com/typeddjango/django-stubs/tree/master/mypy_django_plugin

But, i actually think it's better to treat those fields as `private` and not use them in actual application code. And prefer solutions like `translation.override`. This way - all complexity stays at translation level, which is handled by django and django-modeltranslation. And it compatible with any of typecheckers, like pyright, not only with mypy.

**Comment by ppeczek** [comment]
I agree. Therefore I am closing this issue. Thanks!
