### ISSUE TITLE
Release 0.17.4. for Django 4?

### ISSUE THREAD

**Issue by julianklotz** [deschler/django-modeltranslation#623]
Dear contributors,

as far as I can see the Django 4 deprecation warning has been fixed in https://github.com/deschler/django-modeltranslation/pull/618 already.

It doesn’t break Django 4 installations, but made me take a closer look. Will there be a maintenance release for Django 4 soon?

Cheers, j

**Comment by last-partizan** [comment]
Released!

**Comment by julianklotz** [comment]
lovely! thank you.

**Comment by last-partizan** [comment]
I reverted that fix in 0.17.5, but it should work just fine with django 4.0.
