### ISSUE TITLE
Can't set field defaults

### ISSUE THREAD

**Issue by vic22222** [deschler/django-modeltranslation#640]
I'm using django-modeltranslation CharField in Django and all I want to do is have a default value for each language in case it's null or newly created. I already read the documentation and found nothing, so I tried something like this which clearly doesn't work:

> @register(CustomFields)
> class CustomFieldsTranslationOptions(TranslationOptions):
> &nbsp;&nbsp;&nbsp;&nbsp;fields = ('subscribe_btn_text',)
> &nbsp;&nbsp;&nbsp;&nbsp;fallback_values = {
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'subscribe_btn_text_en': 'Subscribe',
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'subscribe_btn_text_es': 'Suscribir',
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'subscribe_btn_text_fr': "S'abonner",
> &nbsp;&nbsp;&nbsp;&nbsp;}

Just to exemplify, this is what should be happening behind:

![image](https://user-images.githubusercontent.com/85118830/169531352-811ce506-6516-4cd2-a8d5-ec818831d96b.png)

Any idea?
Thanks

**Comment by last-partizan** [comment]
I think, you misunderstood documentation. You're should not provide default values for database text, you should provide translation proxy for case where translation not available. In your example it would be:

```python
from django.utils.translation import gettext_lazy as _

@register(CustomFields)
class CustomFieldsTranslationOptions(TranslationOptions):
    fields = ('subscribe_btn_text',)
    fallback_values = {
        'subscribe_btn_text': _('Subscribe'),
    }
```

https://django-modeltranslation.readthedocs.io/en/latest/usage.html#fallback-val

**Comment by last-partizan** [comment]
No, i think different default values isn't supported at the moment.

Consider using empty default value and translated fallback value. I think it should cover your case.

it works something like this:

```
>>> instance.field 
"Hello"  <- That's fallback english
>>> translation.override("es")
>>> instance.field
"Hola" <- That's fallback spanish
```
