### ISSUE TITLE
Translation of "Home" in Ukrainian

### ISSUE THREAD

**Issue by tan4ik444** [deschler/django-modeltranslation#643]
Hi team, thank you for your module
Could you please correct the translation of the word "Home"  to Ukrainian
The correct translation is "Головна" but not "Домівка" 
The word  "Домівка"  means fiscal home place but all Ukrainian sites use "Головна"  to name the Home page

Thanks a lot
BR
Tania

**Comment by last-partizan** [comment]
Доброго вечора, ми з України :)

Сам модуль django-modeltranslation не робить ніяких перекладів, він тільки дозволяє зберігати переклади в базі даних. Тому вам треба звернутись до того хто наповнює ваш сайт.

Чи я щось неправильно зрозумів, де саме ви б хотіли змінити переклад?

**Comment by tan4ik444** [comment]
Доброго вечора, дуже дякую дуже) Прошу вибачення) Розібралася )))
