### ISSUE TITLE
TabbedUI not working for ForeignKeys

### ISSUE THREAD

**Issue by Hafnernuss** [deschler/django-modeltranslation#660]
Hi,

is there a reason, why the tabbed UI does not work for foreign key fields?
![image](https://user-images.githubusercontent.com/18393658/200787514-8e72b99d-d492-400a-9c35-04bf789897cc.png)

If it's a bug and someone hints me in the right direction, I might be able to fix it myself...

**Comment by last-partizan** [comment]
I'm not sure, should be working. Can you show your admin code?

**Comment by Hafnernuss** [comment]
Sure:
![image](https://user-images.githubusercontent.com/18393658/200810099-616d931e-ed12-4ba5-8a14-1c9dd8a68a9f.png)
 
 
 and translations.py:
 
![image](https://user-images.githubusercontent.com/18393658/200810171-bf5a149a-b9a4-4bab-8cc6-28e76fa1db08.png)

**Comment by last-partizan** [comment]
Looks like everything alright.

Take a look at `modeltranslation/static/modeltranslation/js/tabbed_translation_fields.js`, maybe something here can help understand the problem.

**Comment by Hafnernuss** [comment]
I think I found the issue, and it's not in the `js` file.
I think it's because related fields are wrappers to underlying widgets. In this case, the [RelatedFieldWidgetWrapper](https://github.com/django/django/blob/67da22f08e05018ea968fcacbac9ac37ea925d85/django/contrib/admin/templates/admin/widgets/related_widget_wrapper.html) wraps the [select widget](https://github.com/django/django/blob/main/django/forms/templates/django/forms/widgets/select_option.html).

And [this](https://github.com/deschler/django-modeltranslation/blob/5ab3a45af6262c599f4108de938a93028f9377dd/modeltranslation/admin.py#L98) code tries to attach the `mt` classes to the `RelatedFieldWidgetWrapper`, which wont work, because it does not set attribute classes (can be seen [here](https://github.com/django/django/blob/67da22f08e05018ea968fcacbac9ac37ea925d85/django/contrib/admin/templates/admin/widgets/related_widget_wrapper.html#L2), the classes are hardcoded).

Instead, the classes have to be attached to the wrapped child, or in other terms, instad of [this](https://github.com/deschler/django-modeltranslation/blob/5ab3a45af6262c599f4108de938a93028f9377dd/modeltranslation/admin.py#L119) (`field.widget.attrs['class'] = ' '.join(css_classes)`), `field.widget.widget.attrs['class'] = ' '.join(css_classes)` would be correct.

I'll try to figure out how a sensible pr could look and check if there are any implications...

**Comment by last-partizan** [comment]
https://pypi.org/project/django-modeltranslation/0.18.8b0/

Released beta version, please test.

**Comment by Hafnernuss** [comment]
Seems to work for me, I can report back with more elaborate testing next week.
