### ISSUE TITLE
Cannot turn rewrite off

### ISSUE THREAD

**Issue by uzair-riaz** [deschler/django-modeltranslation#672]
Trying to turn rewrite off for the Multilingual Manager by doing `model.objects.rewrite(False)` doesn't seem to prevent the fields being rewritten. Tried passing `mode=False` as well but no luck. Went through the source code and didn't find anything that should be preventing this. Help?

**django:** 1.11.29
**django-modeltranslation:** 0.13.4

**Comment by diogosilva30** [comment]
How did you solve this?
