### ISSUE TITLE
JSONField getting NULL values

### ISSUE THREAD

**Issue by ruchika2012** [deschler/django-modeltranslation#674]
Hi Team,
 I have created a custom 
MODELTRANSLATION_CUSTOM_FIELDS = ('JSONField')
When i am trying to sync and update the fields, the JSONField is getting NULL values and not getting populated with the original column values. While all the other fields are getting the values from the original column. 
Is there a solution for this? My front end is breaking because of this issue.

**Comment by last-partizan** [comment]
Closed as duplicate #615
