### ISSUE TITLE
Django 4.2: update_or_create doesn't update translated fields

### ISSUE THREAD

**Issue by andrei-shabanski** [deschler/django-modeltranslation#682]
`update_or_create()` doesn't update a translated field if the original field name (without language code) is used in `defaults` argument.

The test below passes in Django 4.1, but not in Django 4.2

```python
    def test_update_or_create(self):
        obj = models.TestModel.objects.create(title_de='old de', title_en='old en')

        obj_1, created = models.TestModel.objects.update_or_create(pk=obj.pk, defaults={'title': 'NEW DE TITLE'})
        assert created is False
        assert obj_1.title == 'NEW DE TITLE'
        assert obj_1.title_en == 'old en'
        assert obj_1.title_de == 'NEW DE TITLE'

        # But if we fetch the real object from db,
        # we will see that `title` hasn't been updated
        obj_2 = models.TestModel.objects.get()
        assert obj_2.title == 'NEW DE TITLE'  # AssertionError: assert 'old de' == 'NEW DE TITLE'
        assert obj_2.title_en == 'old en'
        assert obj_2.title_de == 'NEW DE TITLE'  # AssertionError: assert 'old de' == 'NEW DE TITLE'
```

**Comment by last-partizan** [comment]
Hello, can you try to fix this issue and make a PR?

**Comment by Hopiu** [comment]
@andrei-shabanski, can you confirm if you're currently working on this? If not, I'd be happy to give it a try, provided I can complete it within a reasonable timeframe.

**Comment by andrei-shabanski** [comment]
@Hopiu I'm not working on that yet. Feel free to take a look at the issue

**Comment by last-partizan** [comment]
Please test beta version: `v0.18.10-beta.0`.

**Comment by andrei-shabanski** [comment]
`update_or_create()` is working now.

But generally speaking, should this issue be fixed in the save() method? `obj.save(update_fields=['title'])` still updates only the `title` field, not `title_de`.

**Comment by last-partizan** [comment]
Probably, yes. You can try fixing it and make PR.

**Comment by Hopiu** [comment]
I have only limited knowledge of the codebase. I am hesitant to try fixing the issue in the model's save() method since the responsibility lies with the manager and fields. I'd probably attach a `pre_save` signal to check if `update_fields` is present. However, I prefer to avoid signals if possible. @last-partizan, do you have any other suggestions?

**Comment by last-partizan** [comment]
Take a look at the django `Model.save` method, looks like it's using queryset's `_update()` method with values, so we can try to override that method.

But at that point we don't have access to `update_fields`.

I theory, using `pre_save` could work, and it works it would be simpler than overriding `_update`.

**Comment by Hopiu** [comment]
Sorry @andrei-shabanski, I didn't notice that you already have a solution ready.

**Comment by last-partizan** [comment]
#687 Looks promising, especially if it allows us to remove custom implementation for `update_or_create`.

**Comment by andrei-shabanski** [comment]
Although we don't have access to update_fields, the implementation of `QuerySet._update(values)` will be similar to update_or_create: we just add a translation field of the current language into `values` list if `values` contains the original field only. 
QuerySet._update() is invoked in Model.save() only, so we can safely move changes to `_update`. PR #687 is ready @last-partizan  @Hopiu take a look at it please

One thing that worries me is whether should we update the original field when translation fields are listed in update_fields. I mean the following case:

```
obj.title = 'new value'
obj.save(update_fields={'title_de'})
```

Both implementations don't touch `title` field in the db. The documentation warms about not relying on the original field value though, I'd expect that `title` and `title_de` are always synchronized in the database.

**Comment by Hopiu** [comment]
@andrei-shabanski your PR #687 is much cleaner than mine and doesn't use signals. I think this would be a great addition!

**Comment by sergei-maertens** [comment]
Hi folks - looking at this conversation it appears some PR(s) addressing this have been merged. Should that resolve this issue, or is there more work to be done?
