### ISSUE TITLE
Add a feature to translate the model.fields default value based on field language.

### ISSUE THREAD

**Issue by bart-maykin** [deschler/django-modeltranslation#698]
Currently when the translation fields are created the default value of a model.field will be translated based on the current value.
It would be very handy if this could be changed to the field language of the currently created translation field.

So if you have the following charfield for example:
`description = models.CharField(
    verbose_name=_("description"),
    default=_("Some english text")
)`

And configured your project to support english and dutch with default (and current) language to be english you get the following fields with values:
```
 'description': 'Some english text',
 'description_en': 'Some english text',
 'description_nl': 'Some english text',
```

The wanted outcome would be based on your translation files to something like this for example:
```
 'description': 'Some english text',
 'description_en': 'Some english text',
 'description_nl': 'Wat nederlandse tekst',
```

**Comment by last-partizan** [comment]
Well, that's an interesting feature.

I'm mostly just maintaining this project to ensure it works with latest django versions, but if you're interested, you can try implementing this yourself and create PR, it should be possible to achive you desired result.

**Comment by sergei-maertens** [comment]
Thank you for the quick feedback! We'll come up with a PR

**Comment by sergei-maertens** [comment]
@last-partizan hi! we've implemented this feature, can you give an indication on when you (or another maintainer) might have time to review it? I don't mean to pressure you, just having an ETA is sufficient for us to take it into account for our own planning.

**Comment by sergei-maertens** [comment]
Awesome!
