### ISSUE TITLE
Columns for all languages are added to table

### ISSUE THREAD

**Issue by stephan0h** [deschler/django-modeltranslation#704]
We took a first dive to django-modeltranslation yesterday and we had one problem: we coulnd't prevent it from creating columns for all available languages on our table. Of course we did set the language in settings.py:

```
    LANGUAGES = [
        ('en', _('English')),
        ('de', _('German')),
    ]
    LANGUAGE_CODE = 'de'

    MODELTRANSLATION_LANGUAGES = ('en', 'de')
    MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'
    MODELTRANSLATION_PREPOPULATE_LANGUAGE = 'en'
    MODELTRANSLATION_FALLBACK_LANGUAGES = ('en', 'de')
    MODELTRANSLATION_TRANSLATION_FILES = (
        'salesUnit.translation',
    )

```

How can we correct this behaviour?

**Comment by last-partizan** [comment]
Hi
Try creating a repository with minimal repdocution of this bug. It looks like your setting aren't getting loaded.

**Comment by stephan0h** [comment]
ok, will do. Coming back on this ...

**Comment by stephan0h** [comment]
Problem is solved apparently.
For whatever reason we had the following line in our settings.py:

`from modeltranslation import settings as modeltranslation_settings`

Removing it solved it :-)

**Comment by stephan0h** [comment]
closing it ...
