### ISSUE TITLE
please remove last reference to six on poetry.lock

### ISSUE THREAD

**Issue by a-detiste** [deschler/django-modeltranslation#705]
follow up to

https://github.com/deschler/django-modeltranslation/pull/646/files

**Comment by last-partizan** [comment]
That's a dependency of pytest-cov: https://github.com/pytest-dev/pytest-cov

**Comment by a-detiste** [comment]
Thanks.

Actually `pytest-cov` doesn't need six at all either...

**Comment by a-detiste** [comment]
pytest-cov has been cleansed of the fake dependency

https://github.com/pytest-dev/pytest-cov/commit/ff3fdd8039bb11e93d7a5b06a32091d58e97bfbf

**Comment by last-partizan** [comment]
Oh, nice.

When they release new version with this change we can update our deps.
