### ISSUE TITLE
Question ? : Original field does not contains the default language

### ISSUE THREAD

**Issue by pulse-mind** [deschler/django-modeltranslation#710]
Hello,

Well done for the job done including the documentation.

I have a model with a field 'name', then I get 'name_fr' and 'name_en'. 
My default language is fr.

When I go into the admin, click on create, I fill the name_fr and name_en and click on save. 

I can see that name contains name_en.

I would like that name contains name_fr. 

How to do that ?

**Comment by last-partizan** [comment]
Hi, can you be more specific?

Where do you want to see `name_fr`?

**Comment by pulse-mind** [comment]
Here I am adding a "function" where I set FR and EN version of field name:
<img width="695" alt="Add_Function___Vikta_Admin" src="https://github.com/deschler/django-modeltranslation/assets/22203083/f46a36aa-a8bc-4ee0-8a0d-5032f8a8961c">

After saving the name column contains the same value than the name_en. I'd like to have the name_fr.
<img width="1275" alt="Select_Function_to_change___Vikta_Admin" src="https://github.com/deschler/django-modeltranslation/assets/22203083/d77ac084-8c3e-43fd-9668-cca4f3d7364c">

Is it more specific enough ?

**Comment by last-partizan** [comment]
Yes, that's great!

Looking at your interface (everything in English), i can suggest your current language is English - so, "name" contains English translation.

it's supposed to be depndent on your current language.

**Comment by pulse-mind** [comment]
thanks for your help,
I understand why, on this browser I set English has the default language :D. My other browser are set in French...
