### ISSUE TITLE
Question about Indonesian language code

### ISSUE THREAD

**Issue by kunambi** [deschler/django-modeltranslation#713]
I tried to add Indonesian to my project with the language code "id". However, when I ran `./manage.py makemigrations` it added the fields "title_ind", "description_ind", etc. 

Why did it add the "ind" suffix instead of "id"?

**Comment by last-partizan** [comment]
https://github.com/deschler/django-modeltranslation/commit/902a7c9a72c28a46c948e24c1ac113715df17e48

Two-letter suffix conflicts with django "_id" sufifx, so we replaced it.
