### ISSUE TITLE
Patching of class attribute getters causes error with modeltranslation 0.19.3+ and django-cms

### ISSUE THREAD

**Issue by benzkji** [deschler/django-modeltranslation#745]
I have this issue: https://github.com/django-cms/django-cms/issues/7948

I am not that familiar with admin internals. But to me, it looks like a basic call on an class level attribute causes a getter to be called, which in turn tries to access `self.admin_site`. I was not able to find that code in modeltranslation, though. But pinning <0.19.3 resolves the issue, whereas 0.19.3+ triggers. I was digging in the cms and modeltranslation code for quite a while, to get the infos provided here - but I am not able to find a solution currently. 

It is as well beyond my knowledge to say where this issue should be handled. cms oder here?

**Comment by last-partizan** [comment]
Hello.

Please, provide full traceback and repo with minimal reproduction.

**Comment by benzkji** [comment]
It is not that simple. You'll need to edit a html template in django-cms to see the attribute error - otherwise, django's template system will suppress the error. But yeah, I can try (override that template in my demo project...), it will help everybody understand that strange error.

**Comment by benzkji** [comment]
@last-partizan I have tracked it down (probably), here is a PR with a test: #749

The dict access returns the class itself, which leads to the errors in django-cms (caused by how the template system accesses data, see https://github.com/django/django/blob/main/django/template/base.py#L886, where first, dict access is tried, and not getattr afterwards, if this is successful).

**Comment by last-partizan** [comment]
Closing this as duplicate, let's move to the #748 as it has better reproduction example.
