### ISSUE TITLE
Question: Is it possible to not have "original field" in ModelForm fields?

### ISSUE THREAD

**Issue by khink** [deschler/django-modeltranslation#746]
# Question

For some reason i see the "original field" (untranslated) as a separate field in the edit view. I did not expect this.

![Screenshot from 2024-07-10 10-54-18](https://github.com/deschler/django-modeltranslation/assets/179642/84791299-9b1d-45cb-b098-695afd9ecdaf)

I see on https://django-modeltranslation.readthedocs.io/en/latest/forms.html#modelforms  that i can use `TranslationModelForm` to show only the original field. But how to show all translations but not the original field?

I feel like i'm not understanding the relation between "original field" and "translation field for default language".

# Code

I have a Category class.
```
# models/category.py

class Category(models.Model):
    """Model for categories of lots."""

    name = models.CharField(max_length=255, verbose_name=_("Name"))
    sort_order = models.IntegerField(verbose_name=_("Sort order"))

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")
        ordering = ["sort_order"]
```

Its `name` should be translated:
```
# translation.py

class CategoryTranslationOptions(TranslationOptions):
    fields = ("name",)
    required_languages = ("en", "de", "fr", "nl")


translator.register(Category, CategoryTranslationOptions)
```

My languages are defined so English is the default:
```
# base.py

gettext = lambda s: s
LANGUAGES = (
    ("en", gettext("English")),
    ("de", gettext("German")),
    ("fr", gettext("French")),
    ("nl", gettext("Dutch")),
)
```

The create/edit views:
```
# views/category.py

class CategoryCreateView(CreateView):
    form_class = CategoryForm
    success_url = reverse_lazy("administration:category-list")
    template_name = "administration/category/category_form.html"
    model = Category


class CategoryUpdateView(SuccessMessageMixin, UpdateView):
    form_class = CategoryForm
    success_url = reverse_lazy("administration:category-list")
    template_name = "administration/category/category_form.html"
    model = Category
    success_message = "%(name)s was updated successfully"
```

Template (it uses crispy forms for nicer layout, the original field also shows without crispy):
```
<!-- administration/category/category_form.html -->
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
  {% crispy form %}
{% endblock content %}
```

The create/edit view uses this form:
```
# forms/category.py

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = "__all__"
```

# Versions

```
django==4.2.14
django-modeltranslation==0.19.5
```

**Comment by last-partizan** [comment]
Yes, please follow documentation on Admin integration.

https://django-modeltranslation.readthedocs.io/en/latest/admin.html

**Comment by khink** [comment]
Thanks for taking time to reply so quickly.

However, i'm not trying a Django-admin integration here.
(Reason is we don't want our users in the Django admin interface. We want more control on what we show.)
That's why we use separate view and forms.

Maybe there is some hint in the page you point to, but i haven't found it, could you be more specific?

**Comment by last-partizan** [comment]
Oh, you're building your own forms?

Then you just need to specify only fields you want, or exclude original.

You can use `modeltranslation.utils.get_translation_fields` helper to convert field name to all translated variants, like

```
class Meta:
    fields = [*get_translation_fields("name"]
```

But in your case it's probably better just to use `exclude = ('name', )` if you're using "__all__".

**Comment by khink** [comment]
Yes, we build our own.

Thanks for your pointers.
