### ISSUE TITLE
v0.19.5 introduced error for python 3.8

### ISSUE THREAD

**Issue by adi-** [deschler/django-modeltranslation#753]
https://github.com/deschler/django-modeltranslation/compare/v0.19.4...v0.19.5 introduced following error (python 3.8.10):
```
File "/home/vagrant/.venv/lib/python3.8/site-packages/modeltranslation/_typing.py", line 19, in <module>
    _ListOrTuple: TypeAlias = Union[list[_K], tuple[_K, ...]]
TypeError: 'type' object is not subscriptable
```

**Comment by last-partizan** [comment]
Hello.

I fixes this error in master, but please, pin your dependencies to 0.19.4 as we no longer test against 3.8.

**Comment by adi-** [comment]
Yes, I did, but wanted to inform you :)

Thank for the fix. Waiting for publication!

**Comment by last-partizan** [comment]
This will be published along with other changes sometimes in the future, but it's better for you to pin dependency to 0.19.2.

There's no downside to this, we haven't added any great features, so you aren't missing anything :)

You should upgrade to latest version only after switching to at least python 3.9.
