### ISSUE TITLE
Adding indonesian language leads to admin tabs layout crashing in TabedTranslationAdmin

### ISSUE THREAD

**Issue by flameai** [deschler/django-modeltranslation#763]
If you add Indonesian (Id) to LANGUAGES in Django and try to use TabbedTranslationAdmin there it looks weird 
<img width="842" alt=" 2024-10-15 17 44 47" src="https://github.com/user-attachments/assets/63a8ce3a-e139-4bce-b348-4dfd8db32f7e">

**Comment by last-partizan** [comment]
What's in the browser console? Maybe there's some errors?

**Comment by flameai** [comment]
It's clear in console log.
I spent my day and figured out the bug:
```
--- a/modeltranslation/utils.py
+++ b/modeltranslation/utils.py
@@ -80,7 +80,7 @@ build_localized_verbose_name = lazy(_build_localized_verbose_n
ame, str)
 
 
 def _join_css_class(bits: list[str], offset: int) -> str:
-    if "-".join(bits[-offset:]) in settings.AVAILABLE_LANGUAGES + ["en-us"]:
+    if "-".join(bits[-offset:]) in settings.AVAILABLE_LANGUAGES + ["en-us", "ind"]:
```
It seems you'v forgot to make reverse lookup for Indonesian here in utils.py
Unfortunately I cant make PR to this repo.
It would be nice you make this fix for new version.

Thanks in advance.

**Comment by last-partizan** [comment]
Thanks for a fix, applied it and released new version. Please check.
